from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / "src"))

from lawfirm_os_intake.calibration import (  # noqa: E402
    CalibrationLeakageProof,
    CalibrationPreflightRequest,
)
from lawfirm_os_intake.conflicts import (  # noqa: E402
    ChineseWallProof,
    ChineseWallRequest,
    ChineseWallViolationCandidate,
    SyntheticAdversityGraph,
)
from lawfirm_os_intake.lessons import (  # noqa: E402
    LessonDisclosureProof,
    LessonDisclosureRequest,
    LessonIR,
)
from lawfirm_os_intake.outbox import CrossingProof, CrossingRequest  # noqa: E402
from lawfirm_os_intake.models import (  # noqa: E402
    BenchmarkSnapshotManifest,
    BlockedBudgetAttemptAuditReport,
    BudgetActualComparisonReport,
    BudgetActualAmount,
    BudgetActualCodeComparison,
    BudgetActualPhaseComparison,
    BudgetActualsSource,
    BudgetActualVarianceDriverCandidate,
    BudgetActualVarianceLedgerEvent,
    BudgetActualVarianceLedgerReport,
    BudgetActualVarianceOwnerAdoptionCheck,
    BudgetActualVarianceOwnerAdoptionPacket,
    BudgetActualVarianceOwnerAdoptionReport,
    BudgetCalibrationCorpusArtifact,
    BudgetCalibrationCorpusCheck,
    BudgetCalibrationCorpusReport,
    BudgetCalibrationReadinessCheck,
    BudgetCalibrationReadinessReport,
    BudgetCalibrationStarterPackReport,
    BudgetCalibrationStarterPackStep,
    BudgetChangeLedgerEvent,
    BudgetChangeLedgerReport,
    BudgetCorpusReplayCase,
    BudgetCorpusReplayCaseResult,
    BudgetCorpusReplayCheck,
    BudgetCorpusReplayCommand,
    BudgetCorpusReplayCommandResult,
    BudgetCorpusReplayExecutionCheck,
    BudgetCorpusReplayExecutionReport,
    BudgetCorpusReplayOutputCheck,
    BudgetCorpusReplayPlan,
    BudgetCorpusReplayReviewDecisionTemplate,
    BudgetCorpusReplayReviewOutcomeCheck,
    BudgetCorpusReplayReviewOutcomeRecord,
    BudgetCorpusReplayReviewOutcomeReport,
    BudgetCorpusReplayReviewPacket,
    BudgetCorpusReplayReviewRecommendation,
    BudgetCorpusReplayReviewRedTeamNote,
    BudgetFixtureBindingCandidate,
    BudgetFixtureBindingCandidateReport,
    BudgetFixtureBindingCheck,
    BudgetFixtureBindingHandoffItem,
    BudgetFixtureBindingHandoffReport,
    BudgetFixtureUpdateReviewCheck,
    BudgetFixtureUpdateReviewRecord,
    BudgetFixtureUpdateReviewReport,
    BudgetFixtureUpdatePRPackageCheck,
    BudgetFixtureUpdatePRPackageItem,
    BudgetFixtureUpdatePRPackageReport,
    BudgetCodeBudgetSnapshot,
    BudgetDriverEffect,
    BudgetDriverProfileSummary,
    BudgetGuidelineFlag,
    IntensityNormalizationDemoTotal,
    IntensityNormalizationFamilySignoff,
    IntensityNormalizationMultiplierRow,
    IntensityNormalizationSignoffGateCheck,
    IntensityNormalizationSignoffGateReport,
    IntensityNormalizationSignoffReport,
    BudgetHumanReviewDecisionTemplate,
    BudgetHumanReviewOutcomeCheck,
    BudgetHumanReviewOutcomeDecision,
    BudgetHumanReviewOutcomeOwnerAdoptionCheck,
    BudgetHumanReviewOutcomeOwnerAdoptionPacket,
    BudgetHumanReviewOutcomeOwnerAdoptionReport,
    BudgetHumanReviewOutcomeRecord,
    BudgetHumanReviewOutcomeReport,
    BudgetHumanReviewPacket,
    BudgetHumanReviewPacketCheck,
    BudgetHumanReviewRecommendation,
    BudgetHumanReviewRedTeamNote,
    BudgetPhaseBudgetSnapshot,
    BenchmarkReplayBudgetLineCheck,
    BenchmarkReplayCellCheck,
    BenchmarkReplayCheck,
    BenchmarkReplayReport,
    BudgetLakeAdmissionBundleCheck,
    BudgetLakeAdmissionBundleReport,
    BudgetLakeEvidenceArtifact,
    BudgetLearningLoopActualsSummary,
    BudgetLearningLoopCarrierRejectionSummary,
    BudgetLearningLoopLane,
    BudgetLearningLoopReport,
    BudgetLearningLoopReviewedGateSummary,
    BudgetLifecycleAuditCheck,
    BudgetLifecycleAuditReport,
    BudgetLifecycleFinancialSummary,
    BudgetLifecycleOwnerAdoptionPacket,
    BudgetLifecycleOwnerAdoptionReport,
    BudgetProposal,
    BudgetPreconditionReport,
    BudgetFormMappingReport,
    BudgetFormTemplateAuditReport,
    BudgetDriverLabel,
    BudgetReviewChange,
    BudgetReviewChangeRecord,
    BudgetRevisionDelta,
    BudgetRevisionReport,
    BudgetScenarioSet,
    BudgetSubmissionGuardReport,
    BudgetSupportItem,
    RateBenchmarkCell,
    CarrierAppealResult,
    CarrierCompliantProjection,
    CarrierCompliantProjectionBasis,
    CarrierCompliantProjectionLine,
    CarrierExpectedResponse,
    CarrierCompliantLeverageSummary,
    CarrierPreapprovalReport,
    CarrierPreapprovalRequirement,
    CarrierRejectionDecisionLedgerEvent,
    CarrierRejectionDecisionLedgerReport,
    CarrierRejectionLakeAdmissionCheck,
    CarrierRejectionLakeAdmissionProposal,
    CarrierRejectionLakeAdmissionRecordSpec,
    CarrierRejectionLearningProposal,
    CarrierRejectionLearningReport,
    CarrierRejectionCaptureSourceBundle,
    CarrierRejectionNotice,
    CarrierRejectionOrchestratorConnectorChannel,
    CarrierRejectionOrchestratorInterfaceDraft,
    CarrierRejectionOrchestratorWorkflowStep,
    CarrierRejectionRoadmapAuditCheck,
    CarrierRejectionRoadmapAuditReport,
    CarrierRejectionRoadmapSliceStatus,
    CarrierRejectionReviewDecisionTemplate,
    CarrierRejectionRemediationCase,
    CarrierRejectionReviewPacket,
    CarrierRejectionReviewRecommendation,
    CarrierRejectionReviewRedTeamNote,
    CarrierRejectionSourceRef,
    CarrierResponseReconciliationReport,
    ContractStateDependency,
    ContractStateReport,
    ContextBoundaryReport,
    ContextCounterfactualAuditReport,
    ConflictSeedPacket,
    ConflictSeedLabel,
    CourtListenerDatasetManifest,
    CourtListenerDatasetStrategyCheck,
    CourtListenerDatasetStrategyReport,
    CourtListenerDocketEntry,
    CourtListenerDocketSnapshot,
    CourtListenerFixtureAuditCheck,
    CourtListenerFixtureAuditReport,
    CourtListenerLabelSourceRef,
    CourtListenerSnapshotDocument,
    CourtListenerSnapshotSegment,
    CrossRepoOwnerIssueDraft,
    CrossRepoOwnerIssueDraftQualityCheck,
    CrossRepoOwnerIssueDraftQualityItem,
    CrossRepoOwnerIssueDraftQualityReport,
    CrossRepoOwnerIssueDraftReport,
    CrossRepoOwnerAdoptionPacket,
    CrossRepoOwnerAdoptionReport,
    CrossRepoContractProofReport,
    PilotReviewStoryReport,
    PilotReviewStoryStage,
    CrossRepoPromotionPackage,
    CrossRepoPromotionPackageAuditCheck,
    CrossRepoPromotionPackageAuditReport,
    CrossRepoPromotionProposal,
    DataScopeGateReport,
    DADReviewIssueOutboxCheck,
    DADReviewIssueOutboxMail,
    DADReviewIssueOutboxReport,
    DADReviewIssueRecord,
    PublicDataCacheAuditCheck,
    PublicDataCacheAuditReport,
    PublicDataCacheSourceManifest,
    PublicDerivedSyntheticQAGateCheck,
    PublicDerivedSyntheticQAGateReport,
    SkillsRegistrySpecialistCandidate,
    SkillsRegistrySpecialistReviewCheck,
    SkillsRegistrySpecialistReviewReport,
    PublicSourceMethodologyCheck,
    PublicSourceMethodologyReport,
    PublicSourceMethodologySource,
    PublicMethodologyOwnerHandoffCheck,
    PublicMethodologyOwnerHandoffPacket,
    PublicMethodologyOwnerHandoffReport,
    PublicSyntheticFixtureConversionCheck,
    PublicSyntheticFixtureConversionPlan,
    PublicSyntheticFixtureConversionReviewDecisionTemplate,
    PublicSyntheticFixtureConversionReviewOutcomeCheck,
    PublicSyntheticFixtureConversionReviewOutcomeReport,
    PublicSyntheticFixtureConversionReviewPacket,
    PublicSyntheticFixtureConversionReviewRecommendation,
    PublicSyntheticFixtureConversionReviewRecord,
    PublicSyntheticFixtureConversionReviewRedTeamNote,
    PublicSyntheticFixtureConversionSpec,
    PublicSyntheticFixturePRPackageCheck,
    PublicSyntheticFixturePRPackageItem,
    PublicSyntheticFixturePRPackageReport,
    DeadlineDocketingGuardReport,
    EffectiveContext,
    EvidenceCompletenessReport,
    EvidenceGraph,
    ExceptionLakeCandidate,
    ExceptionLakeHandoffManifest,
    ExceptionLakeMappingPackage,
    ExceptionLakeMappingRule,
    ExceptionLakeReadinessReport,
    FixtureGoldReport,
    FixtureGoldSpec,
    HumanConfirmation,
    HumanGateStatusReport,
    HumanReviewOutcomeRecord,
    IngestionResult,
    IngestionVolumeProfile,
    IntakeLocalCloseoutCheck,
    IntakeLocalCloseoutReport,
    IntakePreflightPacket,
    IntakeStageDocumentLabel,
    IntakeVerticalReadinessArtifactCheck,
    IntakeVerticalReadinessAuditReport,
    IntakeVerticalReadinessSliceStatus,
    LearningOwnerHandoffItem,
    LearningOwnerHandoffPackage,
    LearningOwnerHandoffReport,
    LearningPromotionReadinessCheck,
    LearningPromotionReadinessReport,
    LearningProposedChangeArtifact,
    LearningProposedChangeRedTeamNote,
    LearningProposedChangeSet,
    LearningShadowEvalCase,
    LearningShadowEvalFixtureEvidenceCheck,
    LearningShadowEvalFixtureEvidenceReport,
    LearningShadowEvalFixtureReviewItem,
    LearningShadowEvalFixtureReviewRecord,
    LearningShadowEvalFixtureResult,
    LearningShadowEvalPlan,
    LearningShadowEvalResult,
    LearningShadowEvalResultReport,
    LaborEmploymentBudgetFactAuditCheck,
    LaborEmploymentBudgetFactAuditReport,
    LaborEmploymentBudgetFactFinding,
    LaborEmploymentBudgetFactGap,
    LaborEmploymentBudgetFactGoldCaseResult,
    LaborEmploymentBudgetFactGoldCaseSpec,
    LaborEmploymentBudgetFactGoldCheck,
    LaborEmploymentBudgetFactGoldFindingExpectation,
    LaborEmploymentBudgetFactGoldReport,
    LaborEmploymentBudgetFactGoldSpec,
    LaborEmploymentBudgetFactSource,
    LaborEmploymentBudgetOutputExpectationCase,
    LaborEmploymentBudgetOutputExpectationReport,
    LaborEmploymentBudgetLearningFixtureCase,
    LaborEmploymentBudgetLearningFixtureCheck,
    LaborEmploymentBudgetLearningFixtureManifest,
    LaborEmploymentBudgetLearningFixtureReport,
    LaborEmploymentBudgetLearningFixtureSpec,
    LaborEmploymentBudgetOutcomeReplayExecutionArtifact,
    LaborEmploymentBudgetOutcomeReplayExecutionCase,
    LaborEmploymentBudgetOutcomeReplayExecutionCheck,
    LaborEmploymentBudgetOutcomeReplayExecutionReport,
    LaborEmploymentBudgetOutcomeReplayBuilderBinding,
    LaborEmploymentBudgetOutcomeReplayBuilderBindingCase,
    LaborEmploymentBudgetOutcomeReplayBuilderBindingCheck,
    LaborEmploymentBudgetOutcomeReplayBuilderBindingReport,
    LaborEmploymentBudgetOutcomeReplayBuilderContract,
    LaborEmploymentBudgetOutcomeReplayConfidenceStage,
    LaborEmploymentBudgetOutcomeReplayConfidenceStatusReport,
    LaborEmploymentBudgetOutcomeReplayInputPackCase,
    LaborEmploymentBudgetOutcomeReplayInputPackCheck,
    LaborEmploymentBudgetOutcomeReplayInputPackEntry,
    LaborEmploymentBudgetOutcomeReplayInputPackItem,
    LaborEmploymentBudgetOutcomeReplayInputPackManifest,
    LaborEmploymentBudgetOutcomeReplayInputPackReport,
    LaborEmploymentBudgetOutcomeReplayReadinessCase,
    LaborEmploymentBudgetOutcomeReplayReadinessCheck,
    LaborEmploymentBudgetOutcomeReplayReadinessReport,
    LaborEmploymentBudgetOutcomeReplaySeedManifest,
    LaborEmploymentBudgetOutcomeReplaySeedSpec,
    LaborEmploymentBudgetQAGateBucket,
    LaborEmploymentBudgetQAGateCheck,
    LaborEmploymentBudgetQAGateReport,
    LaborEmploymentNonlinearTemplateAuditCheck,
    LaborEmploymentNonlinearTemplateAuditReport,
    LaborEmploymentNonlinearTemplatePhase,
    LaborEmploymentNonlinearTemplateScenarioGate,
    LaborEmploymentNonlinearTemplateSpec,
    LaborEmploymentNonlinearTemplateSpecItem,
    LaborEmploymentNonlinearTemplateTask,
    LaborEmploymentNonlinearTemplateTierBlock,
    LaborEmploymentExecutableCoverageCase,
    LaborEmploymentExecutableCoverageCheck,
    LaborEmploymentExecutableCoverageFamily,
    LaborEmploymentExecutableCoverageReport,
    LaborEmploymentExecutableBudgetFactBindingCase,
    LaborEmploymentExecutableBudgetFactBindingCaseSpec,
    LaborEmploymentExecutableBudgetFactBindingCheck,
    LaborEmploymentExecutableBudgetFactBindingItem,
    LaborEmploymentExecutableBudgetFactBindingItemSpec,
    LaborEmploymentExecutableBudgetFactBindingManifest,
    LaborEmploymentExecutableBudgetFactBindingReport,
    LaborEmploymentExecutableFixtureAuditCase,
    LaborEmploymentExecutableFixtureAuditCheck,
    LaborEmploymentExecutableFixtureAuditReport,
    LaborEmploymentExecutableFixtureManifest,
    LaborEmploymentExecutableFixtureSpec,
    LaborEmploymentQAMatrixCase,
    LaborEmploymentQAMatrixReport,
    LaborEmploymentSyntheticFixtureCase,
    LaborEmploymentSyntheticFixtureFamilyCoverage,
    LaborEmploymentSyntheticFixtureFamilyPack,
    LaborEmploymentSyntheticFixtureFamilyPackCheck,
    LaborEmploymentSyntheticFixtureFamilyPackReport,
    MatterOpeningReadiness,
    MatterLinkingPreflightCheck,
    MatterLinkingPreflightCluster,
    MatterLinkingPreflightReport,
    MatterLinkKey,
    MatterLinkKeyExtractionCheck,
    MatterLinkKeyExtractionReport,
    MatterLinkKeySet,
    MatterLinkPriorContextPin,
    MatterLinkHumanDecision,
    MatterLinkRunExport,
    MatterClusterProposal,
    MatterLinkDecisionRecord,
    MatterLinkingClusterCheck,
    MatterLinkingClusterReport,
    MatterLinkingClusterReviewDecision,
    MatterLinkingClusterReviewOutcomeCheck,
    MatterLinkingClusterReviewOutcomeRecord,
    MatterLinkingClusterReviewOutcomeReport,
    MatterLinkingQAGateCase,
    MatterLinkingQAGateCheck,
    MatterLinkingQAGateReport,
    MatterLinkingReviewDecision,
    MatterLinkingReviewOutcomeCheck,
    MatterLinkingReviewOutcomeRecord,
    MatterLinkingReviewOutcomeReport,
    EntityComparisonResult,
    EntityNormalizationResult,
    EntityResolutionCorrectionCheck,
    EntityResolutionCorrectionDecision,
    EntityResolutionCorrectionRecord,
    EntityResolutionCorrectionReport,
    ModelAdapterReport,
    NamedTimekeeperRate,
    OrchestratorOwnerReviewBudgetActualLine,
    OrchestratorOwnerReviewBudgetPreconditions,
    OrchestratorOwnerReviewCarrierAppeal,
    OrchestratorOwnerReviewCarrierAppealResult,
    OrchestratorOwnerReviewCarrierRejectionNotice,
    OrchestratorOwnerReviewHumanConfirmation,
    OrchestratorOwnerReviewRequest,
    OrchestratorOwnerReviewSourceRef,
    PartyCandidate,
    PersonTimelineEventLabel,
    PRMergeOrderCheck,
    PRMergeOrderReadinessPacket,
    PRMergeOrderRecommendation,
    PRMergeOrderSharedSurface,
    PRMergeOrderSnapshot,
    PRMergeOrderSnapshotItem,
    PRReadinessDecisionCheck,
    PRReadinessDecisionRecord,
    PRReadinessDecisionReport,
    PRReviewChecklistItem,
    PRReviewChecklistReport,
    RemainingRoadmapCheck,
    RemainingRoadmapItem,
    RemainingRoadmapReport,
    ReviewPackageCompletenessReport,
    ReviewPackageManifest,
    ReviewedLearningGateCandidate,
    ReviewedLearningGateCheck,
    ReviewedLearningGateReport,
    RunEvent,
    RunLedgerIntegrityReport,
    RustFixtureBoundaryFailure,
    RustFixtureBoundaryReport,
    RustFixtureManifestFailure,
    RustFixtureManifestFile,
    RustFixtureManifestIdField,
    RustFixtureManifestReport,
    RustFixtureManifestSkippedFile,
    RustFixtureSnapshotCoherenceFailure,
    RustFixtureSnapshotCoherenceReport,
    RustFixtureSnapshotCoherenceSkippedFile,
    RustToolLadderAuditCheck,
    RustToolLadderAuditReport,
    RustToolLadderConfig,
    RustToolLadderHistoryEvent,
    RustToolLadderTool,
    RustPublicDataCacheCustodyFailure,
    RustPublicDataCacheCustodyReport,
    RustPublicDataCacheCustodySample,
    RustSyntheticIdentityGuardFailure,
    RustSyntheticIdentityGuardReport,
    RustIngestionReadinessReport,
    RustUIBundleSourceHashDetail,
    RustUIBundleSourceHashFailure,
    RustUIBundleSourceHashReport,
    RustTransitionPolicy,
    SafetyGateReport,
    Segment,
    SourceBundle,
    StarterReleaseAuditReport,
    SyntheticIntakeWrapper,
    SyntheticFixtureExpansionCheck,
    SyntheticFixtureDepthAuditReport,
    SyntheticFixtureDepthDimension,
    SyntheticFixtureDepthFamilySummary,
    SyntheticFixtureExpansionHoldoutSpec,
    SyntheticFixtureExpansionManifest,
    SyntheticFixtureExpansionReport,
    SyntheticConfidenceSummaryItem,
    SyntheticConfidenceSummaryReport,
    SyntheticActualsWorkbenchCheck,
    SyntheticActualsWorkbenchReport,
    SyntheticBudgetInputWorkbenchCheck,
    SyntheticBudgetInputWorkbenchContextLane,
    SyntheticBudgetInputWorkbenchLine,
    SyntheticBudgetInputWorkbenchReport,
    SyntheticBudgetConfigurationEntry,
    SyntheticBudgetConfigurationSource,
    SyntheticBudgetConfigurationWorkbenchCheck,
    SyntheticBudgetConfigurationWorkbenchReport,
    SyntheticBudgetConfigurationChange,
    SyntheticBudgetConfigurationChangeCheck,
    SyntheticBudgetConfigurationChangePackage,
    GeneratedSyntheticCase,
    LearningCaptureReport,
    LearningLoopDeliveryPacket,
    LearningLoopHostileSweepReport,
    MLLearnabilityProbeReport,
    SyntheticCasePipelineResult,
    SyntheticCasePipelineSpec,
    SyntheticConfigurationRegenerationBindingReport,
    SyntheticCorpusManifest,
    SyntheticEvalCaptureLedgerEntry,
    SyntheticEvalMetricDelta,
    SyntheticPipelineEvalReport,
    SyntheticConfigurationRegenerationCheck,
    SyntheticGuidelineProjectionWorkbenchCheck,
    SyntheticGuidelineProjectionWorkbenchReport,
    SyntheticGuidelineProjectionWorkbenchSource,
    SyntheticGuidelineProjectionWorkbenchView,
    SyntheticRejectionAppealWorkbenchCase,
    SyntheticRejectionAppealWorkbenchCheck,
    SyntheticRejectionAppealWorkbenchReport,
    SyntheticRateCardWorkbenchCheck,
    SyntheticRateCardWorkbenchReport,
    SyntheticRateCardWorkbenchRow,
    CaseCostDriverCatalog,
    CaseCostDriverSpec,
    CaseSizingEffect,
    CaseSizingReport,
    ProportionalityAssessment,
    SettlementPosture,
    SettlementPostureAnalysis,
    SettlementPostureInput,
    SizedWorkPlan,
    FirmExcelBudgetExport,
    FirmExcelBudgetPhase,
    FirmExcelBudgetTaskRow,
    RouterEvalCaseResult,
    RouterEvalCaseSpec,
    RouterEvaluationReport,
    RouterFamilyAccuracy,
    FirmCheckpointCase,
    FirmCheckpointCaseDisposition,
    FirmCheckpointPacket,
    OCGContractReconciliationReport,
    OCGProposedRuleKind,
    OCGRuleKindExtensionProposal,
    SiblingConformanceReport,
    DeliveryPacket,
    EconomicRegimeCatalog,
    EconomicRegimeProfile,
    SyntheticRateCardWorkbenchStateSummary,
    ValidationSuiteEvidenceReport,
    ValidationSuiteStepEvidence,
    POCQATriageItem,
    POCQATriageReport,
    SyntheticQABlockerReport,
    SyntheticQABlockerRow,
    SyntheticQABlockerReviewDecision,
    SyntheticQABlockerReviewOutcomeRecord,
    SyntheticQABlockerReviewOutcomeReport,
    SyntheticQABundleArtifact,
    SyntheticQABundleReport,
    SyntheticQAReviewRunReport,
    SyntheticQAReviewRunStep,
    UIDemoFixturePromotionItem,
    UIDemoFixturePromotionReport,
    UIDemoFixtureRefreshDetail,
    UIDemoFixtureRefreshReport,
    UIDemoQARecipeFixtureRefreshReport,
    UIReviewDataBundle,
    UIReviewDataBundleDetailReport,
    Crosswalk,
    CrosswalkAuditFinding,
    CrosswalkAuditReport,
    CrosswalkAuditSummary,
    CrosswalkEntry,
    CrosswalkSourceProvenance,
    OCGRuleImpactLine,
    OCGRuleIRAdoptionFinding,
    OCGRuleIRAdoptionReport,
    OCGRuleIRAdoptionSummary,
    OCGSharedRuleIR,
    OCGSharedRuleIRRule,
    QAProductConfidenceGate,
    QAProductConfidenceReport,
    QAReadinessCheck,
    QAReadinessReport,
)

MODELS = {
    "calibration-leakage-proof.schema.json": CalibrationLeakageProof,
    "calibration-preflight-request.schema.json": CalibrationPreflightRequest,
    "lesson-disclosure-proof.schema.json": LessonDisclosureProof,
    "lesson-disclosure-request.schema.json": LessonDisclosureRequest,
    "lesson-ir.schema.json": LessonIR,
    "crossing-proof.schema.json": CrossingProof,
    "crossing-request.schema.json": CrossingRequest,
    "synthetic-adversity-graph.schema.json": SyntheticAdversityGraph,
    "chinese-wall-request.schema.json": ChineseWallRequest,
    "chinese-wall-proof.schema.json": ChineseWallProof,
    "chinese-wall-violation-candidate.schema.json": ChineseWallViolationCandidate,
    "source-bundle.schema.json": SourceBundle,
    "blocked-budget-attempt-audit-report.schema.json": BlockedBudgetAttemptAuditReport,
    "context-counterfactual-audit-report.schema.json": ContextCounterfactualAuditReport,
    "cross-repo-owner-issue-draft.schema.json": CrossRepoOwnerIssueDraft,
    "cross-repo-owner-issue-draft-quality-check.schema.json": (
        CrossRepoOwnerIssueDraftQualityCheck
    ),
    "cross-repo-owner-issue-draft-quality-item.schema.json": (CrossRepoOwnerIssueDraftQualityItem),
    "cross-repo-owner-issue-draft-quality-report.schema.json": (
        CrossRepoOwnerIssueDraftQualityReport
    ),
    "cross-repo-owner-issue-draft-report.schema.json": CrossRepoOwnerIssueDraftReport,
    "cross-repo-owner-adoption-packet.schema.json": CrossRepoOwnerAdoptionPacket,
    "cross-repo-owner-adoption-report.schema.json": CrossRepoOwnerAdoptionReport,
    "pilot-review-story-stage.schema.json": PilotReviewStoryStage,
    "pilot-review-story-report.schema.json": PilotReviewStoryReport,
    "cross-repo-promotion-package.schema.json": CrossRepoPromotionPackage,
    "cross-repo-promotion-package-audit-check.schema.json": CrossRepoPromotionPackageAuditCheck,
    "cross-repo-promotion-package-audit-report.schema.json": CrossRepoPromotionPackageAuditReport,
    "cross-repo-promotion-proposal.schema.json": CrossRepoPromotionProposal,
    "ingestion-result.schema.json": IngestionResult,
    "ingestion-volume-profile.schema.json": IngestionVolumeProfile,
    "intake-local-closeout-check.schema.json": IntakeLocalCloseoutCheck,
    "intake-local-closeout-report.schema.json": IntakeLocalCloseoutReport,
    "intake-vertical-readiness-slice-status.schema.json": (IntakeVerticalReadinessSliceStatus),
    "intake-vertical-readiness-artifact-check.schema.json": (IntakeVerticalReadinessArtifactCheck),
    "intake-vertical-readiness-audit-report.schema.json": (IntakeVerticalReadinessAuditReport),
    "pr-review-checklist-item.schema.json": PRReviewChecklistItem,
    "pr-review-checklist-report.schema.json": PRReviewChecklistReport,
    "pr-merge-order-check.schema.json": PRMergeOrderCheck,
    "pr-merge-order-readiness-packet.schema.json": PRMergeOrderReadinessPacket,
    "pr-merge-order-recommendation.schema.json": PRMergeOrderRecommendation,
    "pr-merge-order-shared-surface.schema.json": PRMergeOrderSharedSurface,
    "pr-merge-order-snapshot.schema.json": PRMergeOrderSnapshot,
    "pr-merge-order-snapshot-item.schema.json": PRMergeOrderSnapshotItem,
    "skills-registry-specialist-candidate.schema.json": SkillsRegistrySpecialistCandidate,
    "skills-registry-specialist-review-check.schema.json": (SkillsRegistrySpecialistReviewCheck),
    "skills-registry-specialist-review-report.schema.json": (SkillsRegistrySpecialistReviewReport),
    "pr-readiness-decision-check.schema.json": PRReadinessDecisionCheck,
    "pr-readiness-decision-record.schema.json": PRReadinessDecisionRecord,
    "pr-readiness-decision-report.schema.json": PRReadinessDecisionReport,
    "remaining-roadmap-check.schema.json": RemainingRoadmapCheck,
    "remaining-roadmap-item.schema.json": RemainingRoadmapItem,
    "remaining-roadmap-report.schema.json": RemainingRoadmapReport,
    "synthetic-fixture-expansion-check.schema.json": SyntheticFixtureExpansionCheck,
    "synthetic-fixture-expansion-holdout-spec.schema.json": (SyntheticFixtureExpansionHoldoutSpec),
    "synthetic-fixture-expansion-manifest.schema.json": SyntheticFixtureExpansionManifest,
    "synthetic-fixture-expansion-report.schema.json": SyntheticFixtureExpansionReport,
    "synthetic-fixture-depth-dimension.schema.json": SyntheticFixtureDepthDimension,
    "synthetic-fixture-depth-family-summary.schema.json": SyntheticFixtureDepthFamilySummary,
    "synthetic-fixture-depth-audit-report.schema.json": SyntheticFixtureDepthAuditReport,
    "synthetic-confidence-summary-item.schema.json": SyntheticConfidenceSummaryItem,
    "synthetic-confidence-summary-report.schema.json": SyntheticConfidenceSummaryReport,
    "synthetic-actuals-workbench-check.schema.json": SyntheticActualsWorkbenchCheck,
    "synthetic-actuals-workbench-report.schema.json": SyntheticActualsWorkbenchReport,
    "synthetic-budget-input-workbench-check.schema.json": SyntheticBudgetInputWorkbenchCheck,
    "synthetic-budget-input-workbench-context-lane.schema.json": (
        SyntheticBudgetInputWorkbenchContextLane
    ),
    "synthetic-budget-input-workbench-line.schema.json": SyntheticBudgetInputWorkbenchLine,
    "synthetic-budget-input-workbench-report.schema.json": SyntheticBudgetInputWorkbenchReport,
    "synthetic-budget-configuration-entry.schema.json": SyntheticBudgetConfigurationEntry,
    "synthetic-budget-configuration-source.schema.json": SyntheticBudgetConfigurationSource,
    "synthetic-budget-configuration-workbench-check.schema.json": SyntheticBudgetConfigurationWorkbenchCheck,
    "synthetic-budget-configuration-workbench-report.schema.json": SyntheticBudgetConfigurationWorkbenchReport,
    "synthetic-budget-configuration-change.schema.json": SyntheticBudgetConfigurationChange,
    "synthetic-budget-configuration-change-check.schema.json": SyntheticBudgetConfigurationChangeCheck,
    "synthetic-budget-configuration-change-package.schema.json": SyntheticBudgetConfigurationChangePackage,
    "synthetic-configuration-regeneration-binding-report.schema.json": SyntheticConfigurationRegenerationBindingReport,
    "synthetic-configuration-regeneration-check.schema.json": SyntheticConfigurationRegenerationCheck,
    "synthetic-guideline-projection-workbench-check.schema.json": SyntheticGuidelineProjectionWorkbenchCheck,
    "synthetic-guideline-projection-workbench-report.schema.json": SyntheticGuidelineProjectionWorkbenchReport,
    "synthetic-guideline-projection-workbench-source.schema.json": SyntheticGuidelineProjectionWorkbenchSource,
    "synthetic-guideline-projection-workbench-view.schema.json": SyntheticGuidelineProjectionWorkbenchView,
    "synthetic-rejection-appeal-workbench-case.schema.json": SyntheticRejectionAppealWorkbenchCase,
    "synthetic-rejection-appeal-workbench-check.schema.json": SyntheticRejectionAppealWorkbenchCheck,
    "synthetic-rejection-appeal-workbench-report.schema.json": SyntheticRejectionAppealWorkbenchReport,
    "synthetic-rate-card-workbench-check.schema.json": SyntheticRateCardWorkbenchCheck,
    "synthetic-rate-card-workbench-report.schema.json": SyntheticRateCardWorkbenchReport,
    "synthetic-rate-card-workbench-row.schema.json": SyntheticRateCardWorkbenchRow,
    "case-cost-driver-catalog.schema.json": CaseCostDriverCatalog,
    "case-cost-driver-spec.schema.json": CaseCostDriverSpec,
    "case-sizing-effect.schema.json": CaseSizingEffect,
    "case-sizing-report.schema.json": CaseSizingReport,
    "proportionality-assessment.schema.json": ProportionalityAssessment,
    "settlement-posture.schema.json": SettlementPosture,
    "settlement-posture-analysis.schema.json": SettlementPostureAnalysis,
    "settlement-posture-input.schema.json": SettlementPostureInput,
    "sized-work-plan.schema.json": SizedWorkPlan,
    "firm-excel-budget-export.schema.json": FirmExcelBudgetExport,
    "firm-excel-budget-phase.schema.json": FirmExcelBudgetPhase,
    "firm-excel-budget-task-row.schema.json": FirmExcelBudgetTaskRow,
    "router-eval-case-result.schema.json": RouterEvalCaseResult,
    "router-eval-case-spec.schema.json": RouterEvalCaseSpec,
    "router-evaluation-report.schema.json": RouterEvaluationReport,
    "router-family-accuracy.schema.json": RouterFamilyAccuracy,
    "firm-checkpoint-case.schema.json": FirmCheckpointCase,
    "firm-checkpoint-case-disposition.schema.json": FirmCheckpointCaseDisposition,
    "firm-checkpoint-packet.schema.json": FirmCheckpointPacket,
    "ocg-contract-reconciliation-report.schema.json": OCGContractReconciliationReport,
    "ocg-proposed-rule-kind.schema.json": OCGProposedRuleKind,
    "ocg-rule-kind-extension-proposal.schema.json": OCGRuleKindExtensionProposal,
    "sibling-conformance-report.schema.json": SiblingConformanceReport,
    "delivery-packet.schema.json": DeliveryPacket,
    "economic-regime-catalog.schema.json": EconomicRegimeCatalog,
    "economic-regime-profile.schema.json": EconomicRegimeProfile,
    "synthetic-rate-card-workbench-state-summary.schema.json": (
        SyntheticRateCardWorkbenchStateSummary
    ),
    "validation-suite-step-evidence.schema.json": ValidationSuiteStepEvidence,
    "validation-suite-evidence-report.schema.json": ValidationSuiteEvidenceReport,
    "poc-qa-triage-item.schema.json": POCQATriageItem,
    "poc-qa-triage-report.schema.json": POCQATriageReport,
    "synthetic-qa-blocker-row.schema.json": SyntheticQABlockerRow,
    "synthetic-qa-blocker-report.schema.json": SyntheticQABlockerReport,
    "synthetic-qa-blocker-review-decision.schema.json": SyntheticQABlockerReviewDecision,
    "synthetic-qa-blocker-review-outcome-record.schema.json": (
        SyntheticQABlockerReviewOutcomeRecord
    ),
    "synthetic-qa-blocker-review-outcome-report.schema.json": (
        SyntheticQABlockerReviewOutcomeReport
    ),
    "synthetic-qa-bundle-artifact.schema.json": SyntheticQABundleArtifact,
    "synthetic-qa-bundle-report.schema.json": SyntheticQABundleReport,
    "synthetic-qa-review-run-step.schema.json": SyntheticQAReviewRunStep,
    "synthetic-qa-review-run-report.schema.json": SyntheticQAReviewRunReport,
    "rust-fixture-boundary-failure.schema.json": RustFixtureBoundaryFailure,
    "rust-fixture-boundary-report.schema.json": RustFixtureBoundaryReport,
    "rust-fixture-manifest-failure.schema.json": RustFixtureManifestFailure,
    "rust-fixture-manifest-file.schema.json": RustFixtureManifestFile,
    "rust-fixture-manifest-id-field.schema.json": RustFixtureManifestIdField,
    "rust-fixture-manifest-report.schema.json": RustFixtureManifestReport,
    "rust-fixture-manifest-skipped-file.schema.json": RustFixtureManifestSkippedFile,
    "rust-fixture-snapshot-coherence-failure.schema.json": (RustFixtureSnapshotCoherenceFailure),
    "rust-fixture-snapshot-coherence-report.schema.json": RustFixtureSnapshotCoherenceReport,
    "rust-fixture-snapshot-coherence-skipped-file.schema.json": (
        RustFixtureSnapshotCoherenceSkippedFile
    ),
    "rust-tool-ladder-audit-check.schema.json": RustToolLadderAuditCheck,
    "rust-tool-ladder-audit-report.schema.json": RustToolLadderAuditReport,
    "rust-tool-ladder-config.schema.json": RustToolLadderConfig,
    "rust-tool-ladder-history-event.schema.json": RustToolLadderHistoryEvent,
    "rust-tool-ladder-tool.schema.json": RustToolLadderTool,
    "rust-public-data-cache-custody-failure.schema.json": RustPublicDataCacheCustodyFailure,
    "rust-public-data-cache-custody-sample.schema.json": RustPublicDataCacheCustodySample,
    "rust-public-data-cache-custody-report.schema.json": RustPublicDataCacheCustodyReport,
    "rust-synthetic-identity-guard-failure.schema.json": RustSyntheticIdentityGuardFailure,
    "rust-synthetic-identity-guard-report.schema.json": RustSyntheticIdentityGuardReport,
    "rust-ui-bundle-source-hash-detail.schema.json": RustUIBundleSourceHashDetail,
    "rust-ui-bundle-source-hash-failure.schema.json": RustUIBundleSourceHashFailure,
    "rust-ui-bundle-source-hash-report.schema.json": RustUIBundleSourceHashReport,
    "intensity-normalization-demo-total.schema.json": IntensityNormalizationDemoTotal,
    "intensity-normalization-family-signoff.schema.json": (IntensityNormalizationFamilySignoff),
    "intensity-normalization-multiplier-row.schema.json": (IntensityNormalizationMultiplierRow),
    "intensity-normalization-signoff-gate-check.schema.json": (
        IntensityNormalizationSignoffGateCheck
    ),
    "intensity-normalization-signoff-gate-report.schema.json": (
        IntensityNormalizationSignoffGateReport
    ),
    "intensity-normalization-signoff-report.schema.json": (IntensityNormalizationSignoffReport),
    "ui-demo-fixture-promotion-item.schema.json": UIDemoFixturePromotionItem,
    "ui-demo-fixture-promotion-report.schema.json": UIDemoFixturePromotionReport,
    "ui-demo-fixture-refresh-detail.schema.json": UIDemoFixtureRefreshDetail,
    "ui-demo-fixture-refresh-report.schema.json": UIDemoFixtureRefreshReport,
    "ui-demo-qa-recipe-fixture-refresh-report.schema.json": (UIDemoQARecipeFixtureRefreshReport),
    "ui-review-data-bundle-detail-report.schema.json": UIReviewDataBundleDetailReport,
    "ui-review-data-bundle.schema.json": UIReviewDataBundle,
    "crosswalk.schema.json": Crosswalk,
    "crosswalk-entry.schema.json": CrosswalkEntry,
    "crosswalk-source-provenance.schema.json": CrosswalkSourceProvenance,
    "crosswalk-audit-finding.schema.json": CrosswalkAuditFinding,
    "crosswalk-audit-report.schema.json": CrosswalkAuditReport,
    "crosswalk-audit-summary.schema.json": CrosswalkAuditSummary,
    "ocg-shared-rule-ir.schema.json": OCGSharedRuleIR,
    "ocg-shared-rule-ir-rule.schema.json": OCGSharedRuleIRRule,
    "ocg-rule-impact-line.schema.json": OCGRuleImpactLine,
    "ocg-rule-ir-adoption-finding.schema.json": OCGRuleIRAdoptionFinding,
    "ocg-rule-ir-adoption-report.schema.json": OCGRuleIRAdoptionReport,
    "ocg-rule-ir-adoption-summary.schema.json": OCGRuleIRAdoptionSummary,
    "qa-readiness-check.schema.json": QAReadinessCheck,
    "qa-readiness-report.schema.json": QAReadinessReport,
    "qa-product-confidence-gate.schema.json": QAProductConfidenceGate,
    "qa-product-confidence-report.schema.json": QAProductConfidenceReport,
    "rust-ingestion-readiness-report.schema.json": RustIngestionReadinessReport,
    "rust-transition-policy.schema.json": RustTransitionPolicy,
    "segment.schema.json": Segment,
    "effective-context.schema.json": EffectiveContext,
    "party-candidate.schema.json": PartyCandidate,
    "contract-state-dependency.schema.json": ContractStateDependency,
    "contract-state-report.schema.json": ContractStateReport,
    "context-boundary-report.schema.json": ContextBoundaryReport,
    "budget-driver-label.schema.json": BudgetDriverLabel,
    "conflict-seed-label.schema.json": ConflictSeedLabel,
    "courtlistener-dataset-manifest.schema.json": CourtListenerDatasetManifest,
    "courtlistener-dataset-strategy-check.schema.json": CourtListenerDatasetStrategyCheck,
    "courtlistener-dataset-strategy-report.schema.json": CourtListenerDatasetStrategyReport,
    "courtlistener-docket-entry.schema.json": CourtListenerDocketEntry,
    "courtlistener-docket-snapshot.schema.json": CourtListenerDocketSnapshot,
    "courtlistener-fixture-audit-check.schema.json": CourtListenerFixtureAuditCheck,
    "courtlistener-fixture-audit-report.schema.json": CourtListenerFixtureAuditReport,
    "courtlistener-label-source-ref.schema.json": CourtListenerLabelSourceRef,
    "courtlistener-snapshot-document.schema.json": CourtListenerSnapshotDocument,
    "courtlistener-snapshot-segment.schema.json": CourtListenerSnapshotSegment,
    "labor-employment-budget-fact-source.schema.json": LaborEmploymentBudgetFactSource,
    "labor-employment-budget-fact-finding.schema.json": LaborEmploymentBudgetFactFinding,
    "labor-employment-budget-fact-gap.schema.json": LaborEmploymentBudgetFactGap,
    "labor-employment-budget-fact-audit-check.schema.json": (LaborEmploymentBudgetFactAuditCheck),
    "labor-employment-budget-fact-audit-report.schema.json": (LaborEmploymentBudgetFactAuditReport),
    "labor-employment-budget-fact-gold-finding-expectation.schema.json": (
        LaborEmploymentBudgetFactGoldFindingExpectation
    ),
    "labor-employment-budget-fact-gold-case-spec.schema.json": (
        LaborEmploymentBudgetFactGoldCaseSpec
    ),
    "labor-employment-budget-fact-gold-spec.schema.json": (LaborEmploymentBudgetFactGoldSpec),
    "labor-employment-budget-fact-gold-case-result.schema.json": (
        LaborEmploymentBudgetFactGoldCaseResult
    ),
    "labor-employment-budget-fact-gold-check.schema.json": (LaborEmploymentBudgetFactGoldCheck),
    "labor-employment-budget-fact-gold-report.schema.json": (LaborEmploymentBudgetFactGoldReport),
    "labor-employment-budget-output-expectation-case.schema.json": (
        LaborEmploymentBudgetOutputExpectationCase
    ),
    "labor-employment-budget-output-expectation-report.schema.json": (
        LaborEmploymentBudgetOutputExpectationReport
    ),
    "labor-employment-budget-qa-gate-bucket.schema.json": LaborEmploymentBudgetQAGateBucket,
    "labor-employment-budget-qa-gate-check.schema.json": LaborEmploymentBudgetQAGateCheck,
    "labor-employment-budget-qa-gate-report.schema.json": LaborEmploymentBudgetQAGateReport,
    "labor-employment-nonlinear-template-tier-block.schema.json": (
        LaborEmploymentNonlinearTemplateTierBlock
    ),
    "labor-employment-nonlinear-template-task.schema.json": (LaborEmploymentNonlinearTemplateTask),
    "labor-employment-nonlinear-template-phase.schema.json": (
        LaborEmploymentNonlinearTemplatePhase
    ),
    "labor-employment-nonlinear-template-scenario-gate.schema.json": (
        LaborEmploymentNonlinearTemplateScenarioGate
    ),
    "labor-employment-nonlinear-template-spec-item.schema.json": (
        LaborEmploymentNonlinearTemplateSpecItem
    ),
    "labor-employment-nonlinear-template-spec.schema.json": (LaborEmploymentNonlinearTemplateSpec),
    "labor-employment-nonlinear-template-audit-check.schema.json": (
        LaborEmploymentNonlinearTemplateAuditCheck
    ),
    "labor-employment-nonlinear-template-audit-report.schema.json": (
        LaborEmploymentNonlinearTemplateAuditReport
    ),
    "labor-employment-budget-learning-fixture-spec.schema.json": (
        LaborEmploymentBudgetLearningFixtureSpec
    ),
    "labor-employment-budget-learning-fixture-manifest.schema.json": (
        LaborEmploymentBudgetLearningFixtureManifest
    ),
    "labor-employment-budget-learning-fixture-case.schema.json": (
        LaborEmploymentBudgetLearningFixtureCase
    ),
    "labor-employment-budget-learning-fixture-check.schema.json": (
        LaborEmploymentBudgetLearningFixtureCheck
    ),
    "labor-employment-budget-learning-fixture-report.schema.json": (
        LaborEmploymentBudgetLearningFixtureReport
    ),
    "labor-employment-budget-outcome-replay-seed-spec.schema.json": (
        LaborEmploymentBudgetOutcomeReplaySeedSpec
    ),
    "labor-employment-budget-outcome-replay-seed-manifest.schema.json": (
        LaborEmploymentBudgetOutcomeReplaySeedManifest
    ),
    "labor-employment-budget-outcome-replay-readiness-case.schema.json": (
        LaborEmploymentBudgetOutcomeReplayReadinessCase
    ),
    "labor-employment-budget-outcome-replay-readiness-check.schema.json": (
        LaborEmploymentBudgetOutcomeReplayReadinessCheck
    ),
    "labor-employment-budget-outcome-replay-readiness-report.schema.json": (
        LaborEmploymentBudgetOutcomeReplayReadinessReport
    ),
    "labor-employment-budget-outcome-replay-execution-artifact.schema.json": (
        LaborEmploymentBudgetOutcomeReplayExecutionArtifact
    ),
    "labor-employment-budget-outcome-replay-execution-case.schema.json": (
        LaborEmploymentBudgetOutcomeReplayExecutionCase
    ),
    "labor-employment-budget-outcome-replay-execution-check.schema.json": (
        LaborEmploymentBudgetOutcomeReplayExecutionCheck
    ),
    "labor-employment-budget-outcome-replay-execution-report.schema.json": (
        LaborEmploymentBudgetOutcomeReplayExecutionReport
    ),
    "labor-employment-budget-outcome-replay-builder-contract.schema.json": (
        LaborEmploymentBudgetOutcomeReplayBuilderContract
    ),
    "labor-employment-budget-outcome-replay-builder-binding.schema.json": (
        LaborEmploymentBudgetOutcomeReplayBuilderBinding
    ),
    "labor-employment-budget-outcome-replay-builder-binding-case.schema.json": (
        LaborEmploymentBudgetOutcomeReplayBuilderBindingCase
    ),
    "labor-employment-budget-outcome-replay-builder-binding-check.schema.json": (
        LaborEmploymentBudgetOutcomeReplayBuilderBindingCheck
    ),
    "labor-employment-budget-outcome-replay-builder-binding-report.schema.json": (
        LaborEmploymentBudgetOutcomeReplayBuilderBindingReport
    ),
    "labor-employment-budget-outcome-replay-confidence-stage.schema.json": (
        LaborEmploymentBudgetOutcomeReplayConfidenceStage
    ),
    "labor-employment-budget-outcome-replay-confidence-status-report.schema.json": (
        LaborEmploymentBudgetOutcomeReplayConfidenceStatusReport
    ),
    "labor-employment-budget-outcome-replay-input-pack-entry.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackEntry
    ),
    "labor-employment-budget-outcome-replay-input-pack-manifest.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackManifest
    ),
    "labor-employment-budget-outcome-replay-input-pack-item.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackItem
    ),
    "labor-employment-budget-outcome-replay-input-pack-case.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackCase
    ),
    "labor-employment-budget-outcome-replay-input-pack-check.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackCheck
    ),
    "labor-employment-budget-outcome-replay-input-pack-report.schema.json": (
        LaborEmploymentBudgetOutcomeReplayInputPackReport
    ),
    "labor-employment-executable-coverage-case.schema.json": (
        LaborEmploymentExecutableCoverageCase
    ),
    "labor-employment-executable-coverage-family.schema.json": (
        LaborEmploymentExecutableCoverageFamily
    ),
    "labor-employment-executable-coverage-check.schema.json": (
        LaborEmploymentExecutableCoverageCheck
    ),
    "labor-employment-executable-coverage-report.schema.json": (
        LaborEmploymentExecutableCoverageReport
    ),
    "labor-employment-executable-budget-fact-binding-item-spec.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingItemSpec
    ),
    "labor-employment-executable-budget-fact-binding-case-spec.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingCaseSpec
    ),
    "labor-employment-executable-budget-fact-binding-manifest.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingManifest
    ),
    "labor-employment-executable-budget-fact-binding-item.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingItem
    ),
    "labor-employment-executable-budget-fact-binding-case.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingCase
    ),
    "labor-employment-executable-budget-fact-binding-check.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingCheck
    ),
    "labor-employment-executable-budget-fact-binding-report.schema.json": (
        LaborEmploymentExecutableBudgetFactBindingReport
    ),
    "labor-employment-executable-fixture-spec.schema.json": (LaborEmploymentExecutableFixtureSpec),
    "labor-employment-executable-fixture-manifest.schema.json": (
        LaborEmploymentExecutableFixtureManifest
    ),
    "labor-employment-executable-fixture-audit-case.schema.json": (
        LaborEmploymentExecutableFixtureAuditCase
    ),
    "labor-employment-executable-fixture-audit-check.schema.json": (
        LaborEmploymentExecutableFixtureAuditCheck
    ),
    "labor-employment-executable-fixture-audit-report.schema.json": (
        LaborEmploymentExecutableFixtureAuditReport
    ),
    "labor-employment-qa-matrix-case.schema.json": LaborEmploymentQAMatrixCase,
    "labor-employment-qa-matrix-report.schema.json": LaborEmploymentQAMatrixReport,
    "labor-employment-synthetic-fixture-case.schema.json": (LaborEmploymentSyntheticFixtureCase),
    "labor-employment-synthetic-fixture-family-pack.schema.json": (
        LaborEmploymentSyntheticFixtureFamilyPack
    ),
    "labor-employment-synthetic-fixture-family-coverage.schema.json": (
        LaborEmploymentSyntheticFixtureFamilyCoverage
    ),
    "labor-employment-synthetic-fixture-family-pack-check.schema.json": (
        LaborEmploymentSyntheticFixtureFamilyPackCheck
    ),
    "labor-employment-synthetic-fixture-family-pack-report.schema.json": (
        LaborEmploymentSyntheticFixtureFamilyPackReport
    ),
    "data-scope-gate-report.schema.json": DataScopeGateReport,
    "public-data-cache-source-manifest.schema.json": PublicDataCacheSourceManifest,
    "public-data-cache-audit-check.schema.json": PublicDataCacheAuditCheck,
    "public-data-cache-audit-report.schema.json": PublicDataCacheAuditReport,
    "matter-linking-preflight-check.schema.json": MatterLinkingPreflightCheck,
    "matter-linking-preflight-cluster.schema.json": MatterLinkingPreflightCluster,
    "matter-linking-preflight-report.schema.json": MatterLinkingPreflightReport,
    "matter-link-key.schema.json": MatterLinkKey,
    "matter-link-key-set.schema.json": MatterLinkKeySet,
    "matter-link-key-extraction-check.schema.json": MatterLinkKeyExtractionCheck,
    "matter-link-key-extraction-report.schema.json": MatterLinkKeyExtractionReport,
    "matter-link-prior-context-pin.schema.json": MatterLinkPriorContextPin,
    "matter-link-human-decision.schema.json": MatterLinkHumanDecision,
    "matter-link-run-export.schema.json": MatterLinkRunExport,
    "matter-link-decision-record.schema.json": MatterLinkDecisionRecord,
    "matter-cluster-proposal.schema.json": MatterClusterProposal,
    "matter-linking-cluster-check.schema.json": MatterLinkingClusterCheck,
    "matter-linking-cluster-report.schema.json": MatterLinkingClusterReport,
    "matter-linking-cluster-review-decision.schema.json": (MatterLinkingClusterReviewDecision),
    "matter-linking-cluster-review-outcome-check.schema.json": (
        MatterLinkingClusterReviewOutcomeCheck
    ),
    "matter-linking-cluster-review-outcome-record.schema.json": (
        MatterLinkingClusterReviewOutcomeRecord
    ),
    "matter-linking-cluster-review-outcome-report.schema.json": (
        MatterLinkingClusterReviewOutcomeReport
    ),
    "entity-normalization-result.schema.json": EntityNormalizationResult,
    "entity-comparison-result.schema.json": EntityComparisonResult,
    "entity-resolution-correction-decision.schema.json": EntityResolutionCorrectionDecision,
    "entity-resolution-correction-record.schema.json": EntityResolutionCorrectionRecord,
    "entity-resolution-correction-check.schema.json": EntityResolutionCorrectionCheck,
    "entity-resolution-correction-report.schema.json": EntityResolutionCorrectionReport,
    "matter-linking-qa-gate-case.schema.json": MatterLinkingQAGateCase,
    "matter-linking-qa-gate-check.schema.json": MatterLinkingQAGateCheck,
    "matter-linking-qa-gate-report.schema.json": MatterLinkingQAGateReport,
    "matter-linking-review-decision.schema.json": MatterLinkingReviewDecision,
    "matter-linking-review-outcome-check.schema.json": MatterLinkingReviewOutcomeCheck,
    "matter-linking-review-outcome-record.schema.json": MatterLinkingReviewOutcomeRecord,
    "matter-linking-review-outcome-report.schema.json": MatterLinkingReviewOutcomeReport,
    "public-source-methodology-source.schema.json": PublicSourceMethodologySource,
    "public-source-methodology-check.schema.json": PublicSourceMethodologyCheck,
    "public-source-methodology-report.schema.json": PublicSourceMethodologyReport,
    "public-methodology-owner-handoff-check.schema.json": (PublicMethodologyOwnerHandoffCheck),
    "public-methodology-owner-handoff-packet.schema.json": (PublicMethodologyOwnerHandoffPacket),
    "public-methodology-owner-handoff-report.schema.json": (PublicMethodologyOwnerHandoffReport),
    "public-synthetic-fixture-conversion-spec.schema.json": (PublicSyntheticFixtureConversionSpec),
    "public-synthetic-fixture-conversion-check.schema.json": (
        PublicSyntheticFixtureConversionCheck
    ),
    "public-synthetic-fixture-conversion-plan.schema.json": (PublicSyntheticFixtureConversionPlan),
    "public-synthetic-fixture-conversion-review-recommendation.schema.json": (
        PublicSyntheticFixtureConversionReviewRecommendation
    ),
    "public-synthetic-fixture-conversion-review-red-team-note.schema.json": (
        PublicSyntheticFixtureConversionReviewRedTeamNote
    ),
    "public-synthetic-fixture-conversion-review-decision-template.schema.json": (
        PublicSyntheticFixtureConversionReviewDecisionTemplate
    ),
    "public-synthetic-fixture-conversion-review-packet.schema.json": (
        PublicSyntheticFixtureConversionReviewPacket
    ),
    "public-synthetic-fixture-conversion-review-record.schema.json": (
        PublicSyntheticFixtureConversionReviewRecord
    ),
    "public-synthetic-fixture-conversion-review-outcome-check.schema.json": (
        PublicSyntheticFixtureConversionReviewOutcomeCheck
    ),
    "public-synthetic-fixture-conversion-review-outcome-report.schema.json": (
        PublicSyntheticFixtureConversionReviewOutcomeReport
    ),
    "public-derived-synthetic-qa-gate-check.schema.json": PublicDerivedSyntheticQAGateCheck,
    "public-derived-synthetic-qa-gate-report.schema.json": PublicDerivedSyntheticQAGateReport,
    "public-synthetic-fixture-pr-package-check.schema.json": PublicSyntheticFixturePRPackageCheck,
    "public-synthetic-fixture-pr-package-item.schema.json": PublicSyntheticFixturePRPackageItem,
    "public-synthetic-fixture-pr-package-report.schema.json": (
        PublicSyntheticFixturePRPackageReport
    ),
    "model-adapter-report.schema.json": ModelAdapterReport,
    "evidence-completeness-report.schema.json": EvidenceCompletenessReport,
    "fixture-gold-spec.schema.json": FixtureGoldSpec,
    "fixture-gold-report.schema.json": FixtureGoldReport,
    "intake-preflight-packet.schema.json": IntakePreflightPacket,
    "intake-stage-document-label.schema.json": IntakeStageDocumentLabel,
    "deadline-docketing-guard-report.schema.json": DeadlineDocketingGuardReport,
    "human-confirmation.schema.json": HumanConfirmation,
    "human-gate-status-report.schema.json": HumanGateStatusReport,
    "human-review-outcome-record.schema.json": HumanReviewOutcomeRecord,
    "conflict-seed-packet.schema.json": ConflictSeedPacket,
    "person-timeline-event-label.schema.json": PersonTimelineEventLabel,
    "synthetic-intake-wrapper.schema.json": SyntheticIntakeWrapper,
    "budget-precondition-report.schema.json": BudgetPreconditionReport,
    "budget-form-mapping-report.schema.json": BudgetFormMappingReport,
    "budget-form-template-audit-report.schema.json": BudgetFormTemplateAuditReport,
    "budget-submission-guard-report.schema.json": BudgetSubmissionGuardReport,
    "matter-opening-readiness.schema.json": MatterOpeningReadiness,
    "legal-budget-proposal.schema.json": BudgetProposal,
    "budget-actual-amount.schema.json": BudgetActualAmount,
    "budget-actuals-source.schema.json": BudgetActualsSource,
    "budget-actual-comparison-report.schema.json": BudgetActualComparisonReport,
    "budget-actual-phase-comparison.schema.json": BudgetActualPhaseComparison,
    "budget-actual-code-comparison.schema.json": BudgetActualCodeComparison,
    "budget-actual-variance-driver-candidate.schema.json": (BudgetActualVarianceDriverCandidate),
    "budget-actual-variance-ledger-event.schema.json": BudgetActualVarianceLedgerEvent,
    "budget-actual-variance-ledger-report.schema.json": BudgetActualVarianceLedgerReport,
    "budget-actual-variance-owner-adoption-check.schema.json": (
        BudgetActualVarianceOwnerAdoptionCheck
    ),
    "budget-actual-variance-owner-adoption-packet.schema.json": (
        BudgetActualVarianceOwnerAdoptionPacket
    ),
    "budget-actual-variance-owner-adoption-report.schema.json": (
        BudgetActualVarianceOwnerAdoptionReport
    ),
    "budget-calibration-corpus-artifact.schema.json": BudgetCalibrationCorpusArtifact,
    "budget-calibration-corpus-check.schema.json": BudgetCalibrationCorpusCheck,
    "budget-calibration-corpus-report.schema.json": BudgetCalibrationCorpusReport,
    "budget-calibration-readiness-check.schema.json": BudgetCalibrationReadinessCheck,
    "budget-calibration-readiness-report.schema.json": BudgetCalibrationReadinessReport,
    "budget-calibration-starter-pack-step.schema.json": BudgetCalibrationStarterPackStep,
    "budget-calibration-starter-pack-report.schema.json": BudgetCalibrationStarterPackReport,
    "budget-change-ledger-event.schema.json": BudgetChangeLedgerEvent,
    "budget-change-ledger-report.schema.json": BudgetChangeLedgerReport,
    "budget-corpus-replay-case.schema.json": BudgetCorpusReplayCase,
    "budget-corpus-replay-case-result.schema.json": BudgetCorpusReplayCaseResult,
    "budget-corpus-replay-check.schema.json": BudgetCorpusReplayCheck,
    "budget-corpus-replay-command.schema.json": BudgetCorpusReplayCommand,
    "budget-corpus-replay-command-result.schema.json": BudgetCorpusReplayCommandResult,
    "budget-corpus-replay-execution-check.schema.json": BudgetCorpusReplayExecutionCheck,
    "budget-corpus-replay-execution-report.schema.json": (BudgetCorpusReplayExecutionReport),
    "budget-corpus-replay-output-check.schema.json": BudgetCorpusReplayOutputCheck,
    "budget-corpus-replay-plan.schema.json": BudgetCorpusReplayPlan,
    "budget-corpus-replay-review-decision-template.schema.json": (
        BudgetCorpusReplayReviewDecisionTemplate
    ),
    "budget-corpus-replay-review-outcome-check.schema.json": (BudgetCorpusReplayReviewOutcomeCheck),
    "budget-corpus-replay-review-outcome-record.schema.json": (
        BudgetCorpusReplayReviewOutcomeRecord
    ),
    "budget-corpus-replay-review-outcome-report.schema.json": (
        BudgetCorpusReplayReviewOutcomeReport
    ),
    "budget-corpus-replay-review-packet.schema.json": BudgetCorpusReplayReviewPacket,
    "budget-corpus-replay-review-recommendation.schema.json": (
        BudgetCorpusReplayReviewRecommendation
    ),
    "budget-corpus-replay-review-red-team-note.schema.json": (BudgetCorpusReplayReviewRedTeamNote),
    "budget-fixture-binding-candidate.schema.json": BudgetFixtureBindingCandidate,
    "budget-fixture-binding-check.schema.json": BudgetFixtureBindingCheck,
    "budget-fixture-binding-candidate-report.schema.json": BudgetFixtureBindingCandidateReport,
    "budget-fixture-binding-handoff-item.schema.json": BudgetFixtureBindingHandoffItem,
    "budget-fixture-binding-handoff-report.schema.json": BudgetFixtureBindingHandoffReport,
    "budget-fixture-update-review-check.schema.json": BudgetFixtureUpdateReviewCheck,
    "budget-fixture-update-review-record.schema.json": BudgetFixtureUpdateReviewRecord,
    "budget-fixture-update-review-report.schema.json": BudgetFixtureUpdateReviewReport,
    "budget-fixture-update-pr-package-check.schema.json": BudgetFixtureUpdatePRPackageCheck,
    "budget-fixture-update-pr-package-item.schema.json": BudgetFixtureUpdatePRPackageItem,
    "budget-fixture-update-pr-package-report.schema.json": (BudgetFixtureUpdatePRPackageReport),
    "budget-review-change.schema.json": BudgetReviewChange,
    "budget-review-change-record.schema.json": BudgetReviewChangeRecord,
    "budget-phase-budget-snapshot.schema.json": BudgetPhaseBudgetSnapshot,
    "budget-code-budget-snapshot.schema.json": BudgetCodeBudgetSnapshot,
    "budget-revision-delta.schema.json": BudgetRevisionDelta,
    "budget-revision-report.schema.json": BudgetRevisionReport,
    "budget-driver-effect.schema.json": BudgetDriverEffect,
    "budget-driver-profile-summary.schema.json": BudgetDriverProfileSummary,
    "budget-guideline-flag.schema.json": BudgetGuidelineFlag,
    "rate-benchmark-cell.schema.json": RateBenchmarkCell,
    "benchmark-snapshot-manifest.schema.json": BenchmarkSnapshotManifest,
    "benchmark-replay-cell-check.schema.json": BenchmarkReplayCellCheck,
    "benchmark-replay-budget-line-check.schema.json": BenchmarkReplayBudgetLineCheck,
    "benchmark-replay-check.schema.json": BenchmarkReplayCheck,
    "benchmark-replay-report.schema.json": BenchmarkReplayReport,
    "budget-lake-evidence-artifact.schema.json": BudgetLakeEvidenceArtifact,
    "budget-lake-admission-bundle-check.schema.json": BudgetLakeAdmissionBundleCheck,
    "budget-lake-admission-bundle-report.schema.json": BudgetLakeAdmissionBundleReport,
    "budget-learning-loop-actuals-summary.schema.json": BudgetLearningLoopActualsSummary,
    "budget-learning-loop-carrier-rejection-summary.schema.json": (
        BudgetLearningLoopCarrierRejectionSummary
    ),
    "budget-learning-loop-reviewed-gate-summary.schema.json": (
        BudgetLearningLoopReviewedGateSummary
    ),
    "budget-learning-loop-lane.schema.json": BudgetLearningLoopLane,
    "budget-learning-loop-report.schema.json": BudgetLearningLoopReport,
    "budget-lifecycle-audit-check.schema.json": BudgetLifecycleAuditCheck,
    "budget-lifecycle-financial-summary.schema.json": BudgetLifecycleFinancialSummary,
    "budget-lifecycle-audit-report.schema.json": BudgetLifecycleAuditReport,
    "budget-human-review-packet-check.schema.json": BudgetHumanReviewPacketCheck,
    "budget-human-review-recommendation.schema.json": BudgetHumanReviewRecommendation,
    "budget-human-review-red-team-note.schema.json": BudgetHumanReviewRedTeamNote,
    "budget-human-review-decision-template.schema.json": BudgetHumanReviewDecisionTemplate,
    "budget-human-review-packet.schema.json": BudgetHumanReviewPacket,
    "budget-human-review-outcome-decision.schema.json": BudgetHumanReviewOutcomeDecision,
    "budget-human-review-outcome-record.schema.json": BudgetHumanReviewOutcomeRecord,
    "budget-human-review-outcome-check.schema.json": BudgetHumanReviewOutcomeCheck,
    "budget-human-review-outcome-report.schema.json": BudgetHumanReviewOutcomeReport,
    "budget-human-review-outcome-owner-adoption-check.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionCheck
    ),
    "budget-human-review-outcome-owner-adoption-packet.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionPacket
    ),
    "budget-human-review-outcome-owner-adoption-report.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionReport
    ),
    "budget-lifecycle-owner-adoption-packet.schema.json": (BudgetLifecycleOwnerAdoptionPacket),
    "budget-lifecycle-owner-adoption-report.schema.json": (BudgetLifecycleOwnerAdoptionReport),
    "carrier-compliant-projection.schema.json": CarrierCompliantProjection,
    "carrier-compliant-projection-basis.schema.json": CarrierCompliantProjectionBasis,
    "carrier-compliant-leverage-summary.schema.json": CarrierCompliantLeverageSummary,
    "carrier-compliant-projection-line.schema.json": CarrierCompliantProjectionLine,
    "carrier-preapproval-requirement.schema.json": CarrierPreapprovalRequirement,
    "carrier-preapproval-report.schema.json": CarrierPreapprovalReport,
    "named-timekeeper-rate.schema.json": NamedTimekeeperRate,
    "budget-scenario-set.schema.json": BudgetScenarioSet,
    "budget-support-item.schema.json": BudgetSupportItem,
    "carrier-expected-response.schema.json": CarrierExpectedResponse,
    "carrier-rejection-source-ref.schema.json": CarrierRejectionSourceRef,
    "carrier-rejection-notice.schema.json": CarrierRejectionNotice,
    "carrier-appeal-result.schema.json": CarrierAppealResult,
    "carrier-rejection-capture-source-bundle.schema.json": CarrierRejectionCaptureSourceBundle,
    "carrier-rejection-decision-ledger-event.schema.json": (CarrierRejectionDecisionLedgerEvent),
    "carrier-rejection-decision-ledger-report.schema.json": (CarrierRejectionDecisionLedgerReport),
    "carrier-rejection-remediation-case.schema.json": CarrierRejectionRemediationCase,
    "carrier-response-reconciliation-report.schema.json": CarrierResponseReconciliationReport,
    "carrier-rejection-review-recommendation.schema.json": (CarrierRejectionReviewRecommendation),
    "carrier-rejection-review-red-team-note.schema.json": CarrierRejectionReviewRedTeamNote,
    "carrier-rejection-review-decision-template.schema.json": (
        CarrierRejectionReviewDecisionTemplate
    ),
    "carrier-rejection-review-packet.schema.json": CarrierRejectionReviewPacket,
    "carrier-rejection-learning-proposal.schema.json": CarrierRejectionLearningProposal,
    "carrier-rejection-learning-report.schema.json": CarrierRejectionLearningReport,
    "carrier-rejection-lake-admission-record-spec.schema.json": (
        CarrierRejectionLakeAdmissionRecordSpec
    ),
    "carrier-rejection-lake-admission-check.schema.json": CarrierRejectionLakeAdmissionCheck,
    "carrier-rejection-lake-admission-proposal.schema.json": (
        CarrierRejectionLakeAdmissionProposal
    ),
    "carrier-rejection-orchestrator-connector-channel.schema.json": (
        CarrierRejectionOrchestratorConnectorChannel
    ),
    "carrier-rejection-orchestrator-workflow-step.schema.json": (
        CarrierRejectionOrchestratorWorkflowStep
    ),
    "carrier-rejection-orchestrator-interface-draft.schema.json": (
        CarrierRejectionOrchestratorInterfaceDraft
    ),
    "orchestrator-owner-review-source-ref.schema.json": OrchestratorOwnerReviewSourceRef,
    "orchestrator-owner-review-human-confirmation.schema.json": (
        OrchestratorOwnerReviewHumanConfirmation
    ),
    "orchestrator-owner-review-budget-preconditions.schema.json": (
        OrchestratorOwnerReviewBudgetPreconditions
    ),
    "orchestrator-owner-review-budget-actual-line.schema.json": (
        OrchestratorOwnerReviewBudgetActualLine
    ),
    "orchestrator-owner-review-carrier-appeal.schema.json": OrchestratorOwnerReviewCarrierAppeal,
    "orchestrator-owner-review-carrier-appeal-result.schema.json": (
        OrchestratorOwnerReviewCarrierAppealResult
    ),
    "orchestrator-owner-review-carrier-rejection-notice.schema.json": (
        OrchestratorOwnerReviewCarrierRejectionNotice
    ),
    "orchestrator-owner-review-request.schema.json": OrchestratorOwnerReviewRequest,
    "cross-repo-contract-proof-report.schema.json": CrossRepoContractProofReport,
    "carrier-rejection-roadmap-slice-status.schema.json": (CarrierRejectionRoadmapSliceStatus),
    "carrier-rejection-roadmap-audit-check.schema.json": CarrierRejectionRoadmapAuditCheck,
    "carrier-rejection-roadmap-audit-report.schema.json": (CarrierRejectionRoadmapAuditReport),
    "evidence-graph.schema.json": EvidenceGraph,
    "run-ledger-event.schema.json": RunEvent,
    "run-ledger-integrity-report.schema.json": RunLedgerIntegrityReport,
    "dad-review-issue-record.schema.json": DADReviewIssueRecord,
    "dad-review-issue-outbox-mail.schema.json": DADReviewIssueOutboxMail,
    "dad-review-issue-outbox-check.schema.json": DADReviewIssueOutboxCheck,
    "dad-review-issue-outbox-report.schema.json": DADReviewIssueOutboxReport,
    "exception-lake-candidate.schema.json": ExceptionLakeCandidate,
    "exception-lake-readiness-report.schema.json": ExceptionLakeReadinessReport,
    "exception-lake-handoff-manifest.schema.json": ExceptionLakeHandoffManifest,
    "exception-lake-mapping-package.schema.json": ExceptionLakeMappingPackage,
    "exception-lake-mapping-rule.schema.json": ExceptionLakeMappingRule,
    "review-package-manifest.schema.json": ReviewPackageManifest,
    "review-package-completeness-report.schema.json": ReviewPackageCompletenessReport,
    "reviewed-learning-gate-candidate.schema.json": ReviewedLearningGateCandidate,
    "reviewed-learning-gate-check.schema.json": ReviewedLearningGateCheck,
    "reviewed-learning-gate-report.schema.json": ReviewedLearningGateReport,
    "learning-shadow-eval-case.schema.json": LearningShadowEvalCase,
    "learning-shadow-eval-plan.schema.json": LearningShadowEvalPlan,
    "learning-promotion-readiness-check.schema.json": LearningPromotionReadinessCheck,
    "learning-promotion-readiness-report.schema.json": LearningPromotionReadinessReport,
    "learning-proposed-change-red-team-note.schema.json": (LearningProposedChangeRedTeamNote),
    "learning-proposed-change-artifact.schema.json": LearningProposedChangeArtifact,
    "learning-proposed-change-set.schema.json": LearningProposedChangeSet,
    "learning-shadow-eval-fixture-result.schema.json": LearningShadowEvalFixtureResult,
    "learning-shadow-eval-fixture-review-item.schema.json": (LearningShadowEvalFixtureReviewItem),
    "learning-shadow-eval-fixture-review-record.schema.json": (
        LearningShadowEvalFixtureReviewRecord
    ),
    "learning-shadow-eval-fixture-evidence-check.schema.json": (
        LearningShadowEvalFixtureEvidenceCheck
    ),
    "learning-shadow-eval-fixture-evidence-report.schema.json": (
        LearningShadowEvalFixtureEvidenceReport
    ),
    "learning-shadow-eval-result.schema.json": LearningShadowEvalResult,
    "learning-shadow-eval-result-report.schema.json": LearningShadowEvalResultReport,
    "learning-owner-handoff-item.schema.json": LearningOwnerHandoffItem,
    "learning-owner-handoff-package.schema.json": LearningOwnerHandoffPackage,
    "learning-owner-handoff-report.schema.json": LearningOwnerHandoffReport,
    "starter-release-audit-report.schema.json": StarterReleaseAuditReport,
    "safety-gate-report.schema.json": SafetyGateReport,
    "synthetic-case-pipeline-spec.schema.json": SyntheticCasePipelineSpec,
    "synthetic-case-pipeline-result.schema.json": SyntheticCasePipelineResult,
    "generated-synthetic-case.schema.json": GeneratedSyntheticCase,
    "synthetic-corpus-manifest.schema.json": SyntheticCorpusManifest,
    "synthetic-pipeline-eval-report.schema.json": SyntheticPipelineEvalReport,
    "synthetic-eval-capture-ledger-entry.schema.json": SyntheticEvalCaptureLedgerEntry,
    "synthetic-eval-metric-delta.schema.json": SyntheticEvalMetricDelta,
    "ml-learnability-probe-report.schema.json": MLLearnabilityProbeReport,
    "learning-capture-report.schema.json": LearningCaptureReport,
    "learning-loop-hostile-sweep-report.schema.json": LearningLoopHostileSweepReport,
    "learning-loop-delivery-packet.schema.json": LearningLoopDeliveryPacket,
}


def main() -> int:
    target = ROOT / "schemas"
    target.mkdir(exist_ok=True)
    for filename, model in MODELS.items():
        (target / filename).write_text(
            json.dumps(model.model_json_schema(), indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    print(f"exported {len(MODELS)} schemas to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
