from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / "src"))

from lawfirm_os_intake.models import (  # noqa: E402
    BlockedBudgetAttemptAuditReport,
    BudgetActualComparisonReport,
    BudgetActualAmount,
    BudgetActualCodeComparison,
    BudgetActualPhaseComparison,
    BudgetActualsSource,
    BudgetActualVarianceDriverCandidate,
    BudgetActualVarianceLedgerEvent,
    BudgetActualVarianceLedgerReport,
    BudgetActualVarianceOwnerAdoptionCheck,
    BudgetActualVarianceOwnerAdoptionPacket,
    BudgetActualVarianceOwnerAdoptionReport,
    BudgetCalibrationCorpusArtifact,
    BudgetCalibrationCorpusCheck,
    BudgetCalibrationCorpusReport,
    BudgetCalibrationReadinessCheck,
    BudgetCalibrationReadinessReport,
    BudgetChangeLedgerEvent,
    BudgetChangeLedgerReport,
    BudgetCorpusReplayCase,
    BudgetCorpusReplayCaseResult,
    BudgetCorpusReplayCheck,
    BudgetCorpusReplayCommand,
    BudgetCorpusReplayCommandResult,
    BudgetCorpusReplayExecutionCheck,
    BudgetCorpusReplayExecutionReport,
    BudgetCorpusReplayOutputCheck,
    BudgetCorpusReplayPlan,
    BudgetCorpusReplayReviewDecisionTemplate,
    BudgetCorpusReplayReviewOutcomeCheck,
    BudgetCorpusReplayReviewOutcomeRecord,
    BudgetCorpusReplayReviewOutcomeReport,
    BudgetCorpusReplayReviewPacket,
    BudgetCorpusReplayReviewRecommendation,
    BudgetCorpusReplayReviewRedTeamNote,
    BudgetFixtureBindingCandidate,
    BudgetFixtureBindingCandidateReport,
    BudgetFixtureBindingCheck,
    BudgetFixtureBindingHandoffItem,
    BudgetFixtureBindingHandoffReport,
    BudgetFixtureUpdateReviewCheck,
    BudgetFixtureUpdateReviewRecord,
    BudgetFixtureUpdateReviewReport,
    BudgetFixtureUpdatePRPackageCheck,
    BudgetFixtureUpdatePRPackageItem,
    BudgetFixtureUpdatePRPackageReport,
    BudgetCodeBudgetSnapshot,
    BudgetDriverEffect,
    BudgetDriverProfileSummary,
    BudgetGuidelineFlag,
    BudgetHumanReviewDecisionTemplate,
    BudgetHumanReviewOutcomeCheck,
    BudgetHumanReviewOutcomeDecision,
    BudgetHumanReviewOutcomeOwnerAdoptionCheck,
    BudgetHumanReviewOutcomeOwnerAdoptionPacket,
    BudgetHumanReviewOutcomeOwnerAdoptionReport,
    BudgetHumanReviewOutcomeRecord,
    BudgetHumanReviewOutcomeReport,
    BudgetHumanReviewPacket,
    BudgetHumanReviewPacketCheck,
    BudgetHumanReviewRecommendation,
    BudgetHumanReviewRedTeamNote,
    BudgetPhaseBudgetSnapshot,
    BudgetLakeAdmissionBundleCheck,
    BudgetLakeAdmissionBundleReport,
    BudgetLakeEvidenceArtifact,
    BudgetLifecycleAuditCheck,
    BudgetLifecycleAuditReport,
    BudgetLifecycleFinancialSummary,
    BudgetLifecycleOwnerAdoptionPacket,
    BudgetLifecycleOwnerAdoptionReport,
    BudgetProposal,
    BudgetPreconditionReport,
    BudgetFormMappingReport,
    BudgetFormTemplateAuditReport,
    BudgetDriverLabel,
    BudgetReviewChange,
    BudgetReviewChangeRecord,
    BudgetRevisionDelta,
    BudgetRevisionReport,
    BudgetScenarioSet,
    BudgetSubmissionGuardReport,
    BudgetSupportItem,
    CarrierAppealResult,
    CarrierCompliantProjection,
    CarrierCompliantProjectionBasis,
    CarrierCompliantProjectionLine,
    CarrierExpectedResponse,
    CarrierCompliantLeverageSummary,
    CarrierPreapprovalReport,
    CarrierPreapprovalRequirement,
    CarrierRejectionDecisionLedgerEvent,
    CarrierRejectionDecisionLedgerReport,
    CarrierRejectionLakeAdmissionCheck,
    CarrierRejectionLakeAdmissionProposal,
    CarrierRejectionLakeAdmissionRecordSpec,
    CarrierRejectionLearningProposal,
    CarrierRejectionLearningReport,
    CarrierRejectionCaptureSourceBundle,
    CarrierRejectionNotice,
    CarrierRejectionOrchestratorConnectorChannel,
    CarrierRejectionOrchestratorInterfaceDraft,
    CarrierRejectionOrchestratorWorkflowStep,
    CarrierRejectionRoadmapAuditCheck,
    CarrierRejectionRoadmapAuditReport,
    CarrierRejectionRoadmapSliceStatus,
    CarrierRejectionReviewDecisionTemplate,
    CarrierRejectionRemediationCase,
    CarrierRejectionReviewPacket,
    CarrierRejectionReviewRecommendation,
    CarrierRejectionReviewRedTeamNote,
    CarrierRejectionSourceRef,
    CarrierResponseReconciliationReport,
    ContractStateDependency,
    ContractStateReport,
    ContextBoundaryReport,
    ContextCounterfactualAuditReport,
    ConflictSeedPacket,
    ConflictSeedLabel,
    CourtListenerDatasetManifest,
    CourtListenerDatasetStrategyCheck,
    CourtListenerDatasetStrategyReport,
    CourtListenerDocketEntry,
    CourtListenerDocketSnapshot,
    CourtListenerFixtureAuditCheck,
    CourtListenerFixtureAuditReport,
    CourtListenerLabelSourceRef,
    CourtListenerSnapshotDocument,
    CourtListenerSnapshotSegment,
    CrossRepoOwnerIssueDraft,
    CrossRepoOwnerIssueDraftQualityCheck,
    CrossRepoOwnerIssueDraftQualityItem,
    CrossRepoOwnerIssueDraftQualityReport,
    CrossRepoOwnerIssueDraftReport,
    CrossRepoOwnerAdoptionPacket,
    CrossRepoOwnerAdoptionReport,
    CrossRepoPromotionPackage,
    CrossRepoPromotionProposal,
    DataScopeGateReport,
    PublicSourceMethodologyCheck,
    PublicSourceMethodologyReport,
    PublicSourceMethodologySource,
    PublicSyntheticFixtureConversionCheck,
    PublicSyntheticFixtureConversionPlan,
    PublicSyntheticFixtureConversionReviewDecisionTemplate,
    PublicSyntheticFixtureConversionReviewOutcomeCheck,
    PublicSyntheticFixtureConversionReviewOutcomeReport,
    PublicSyntheticFixtureConversionReviewPacket,
    PublicSyntheticFixtureConversionReviewRecommendation,
    PublicSyntheticFixtureConversionReviewRecord,
    PublicSyntheticFixtureConversionReviewRedTeamNote,
    PublicSyntheticFixtureConversionSpec,
    PublicSyntheticFixturePRPackageCheck,
    PublicSyntheticFixturePRPackageItem,
    PublicSyntheticFixturePRPackageReport,
    DeadlineDocketingGuardReport,
    EffectiveContext,
    EvidenceCompletenessReport,
    EvidenceGraph,
    ExceptionLakeCandidate,
    ExceptionLakeHandoffManifest,
    ExceptionLakeMappingPackage,
    ExceptionLakeMappingRule,
    ExceptionLakeReadinessReport,
    FixtureGoldReport,
    FixtureGoldSpec,
    HumanConfirmation,
    HumanGateStatusReport,
    HumanReviewOutcomeRecord,
    IngestionResult,
    IngestionVolumeProfile,
    IntakeLocalCloseoutCheck,
    IntakeLocalCloseoutReport,
    IntakePreflightPacket,
    IntakeStageDocumentLabel,
    IntakeVerticalReadinessArtifactCheck,
    IntakeVerticalReadinessAuditReport,
    IntakeVerticalReadinessSliceStatus,
    LearningOwnerHandoffItem,
    LearningOwnerHandoffPackage,
    LearningOwnerHandoffReport,
    LearningPromotionReadinessCheck,
    LearningPromotionReadinessReport,
    LearningProposedChangeArtifact,
    LearningProposedChangeRedTeamNote,
    LearningProposedChangeSet,
    LearningShadowEvalCase,
    LearningShadowEvalFixtureEvidenceCheck,
    LearningShadowEvalFixtureEvidenceReport,
    LearningShadowEvalFixtureReviewItem,
    LearningShadowEvalFixtureReviewRecord,
    LearningShadowEvalFixtureResult,
    LearningShadowEvalPlan,
    LearningShadowEvalResult,
    LearningShadowEvalResultReport,
    LaborEmploymentBudgetFactAuditCheck,
    LaborEmploymentBudgetFactAuditReport,
    LaborEmploymentBudgetFactFinding,
    LaborEmploymentBudgetFactGap,
    LaborEmploymentBudgetFactSource,
    MatterOpeningReadiness,
    ModelAdapterReport,
    NamedTimekeeperRate,
    OrchestratorOwnerReviewBudgetActualLine,
    OrchestratorOwnerReviewBudgetPreconditions,
    OrchestratorOwnerReviewCarrierAppeal,
    OrchestratorOwnerReviewCarrierAppealResult,
    OrchestratorOwnerReviewCarrierRejectionNotice,
    OrchestratorOwnerReviewHumanConfirmation,
    OrchestratorOwnerReviewRequest,
    OrchestratorOwnerReviewSourceRef,
    PartyCandidate,
    PersonTimelineEventLabel,
    PRReadinessDecisionCheck,
    PRReadinessDecisionRecord,
    PRReadinessDecisionReport,
    PRReviewChecklistItem,
    PRReviewChecklistReport,
    RemainingRoadmapCheck,
    RemainingRoadmapItem,
    RemainingRoadmapReport,
    ReviewPackageCompletenessReport,
    ReviewPackageManifest,
    ReviewedLearningGateCandidate,
    ReviewedLearningGateCheck,
    ReviewedLearningGateReport,
    RunEvent,
    RunLedgerIntegrityReport,
    RustIngestionReadinessReport,
    RustTransitionPolicy,
    SafetyGateReport,
    Segment,
    SourceBundle,
    StarterReleaseAuditReport,
    SyntheticIntakeWrapper,
    SyntheticFixtureExpansionCheck,
    SyntheticFixtureDepthAuditReport,
    SyntheticFixtureDepthDimension,
    SyntheticFixtureDepthFamilySummary,
    SyntheticFixtureExpansionHoldoutSpec,
    SyntheticFixtureExpansionManifest,
    SyntheticFixtureExpansionReport,
)

MODELS = {
    "source-bundle.schema.json": SourceBundle,
    "blocked-budget-attempt-audit-report.schema.json": BlockedBudgetAttemptAuditReport,
    "context-counterfactual-audit-report.schema.json": ContextCounterfactualAuditReport,
    "cross-repo-owner-issue-draft.schema.json": CrossRepoOwnerIssueDraft,
    "cross-repo-owner-issue-draft-quality-check.schema.json": (
        CrossRepoOwnerIssueDraftQualityCheck
    ),
    "cross-repo-owner-issue-draft-quality-item.schema.json": (CrossRepoOwnerIssueDraftQualityItem),
    "cross-repo-owner-issue-draft-quality-report.schema.json": (
        CrossRepoOwnerIssueDraftQualityReport
    ),
    "cross-repo-owner-issue-draft-report.schema.json": CrossRepoOwnerIssueDraftReport,
    "cross-repo-owner-adoption-packet.schema.json": CrossRepoOwnerAdoptionPacket,
    "cross-repo-owner-adoption-report.schema.json": CrossRepoOwnerAdoptionReport,
    "cross-repo-promotion-package.schema.json": CrossRepoPromotionPackage,
    "cross-repo-promotion-proposal.schema.json": CrossRepoPromotionProposal,
    "ingestion-result.schema.json": IngestionResult,
    "ingestion-volume-profile.schema.json": IngestionVolumeProfile,
    "intake-local-closeout-check.schema.json": IntakeLocalCloseoutCheck,
    "intake-local-closeout-report.schema.json": IntakeLocalCloseoutReport,
    "intake-vertical-readiness-slice-status.schema.json": (IntakeVerticalReadinessSliceStatus),
    "intake-vertical-readiness-artifact-check.schema.json": (IntakeVerticalReadinessArtifactCheck),
    "intake-vertical-readiness-audit-report.schema.json": (IntakeVerticalReadinessAuditReport),
    "pr-review-checklist-item.schema.json": PRReviewChecklistItem,
    "pr-review-checklist-report.schema.json": PRReviewChecklistReport,
    "pr-readiness-decision-check.schema.json": PRReadinessDecisionCheck,
    "pr-readiness-decision-record.schema.json": PRReadinessDecisionRecord,
    "pr-readiness-decision-report.schema.json": PRReadinessDecisionReport,
    "remaining-roadmap-check.schema.json": RemainingRoadmapCheck,
    "remaining-roadmap-item.schema.json": RemainingRoadmapItem,
    "remaining-roadmap-report.schema.json": RemainingRoadmapReport,
    "synthetic-fixture-expansion-check.schema.json": SyntheticFixtureExpansionCheck,
    "synthetic-fixture-expansion-holdout-spec.schema.json": (SyntheticFixtureExpansionHoldoutSpec),
    "synthetic-fixture-expansion-manifest.schema.json": SyntheticFixtureExpansionManifest,
    "synthetic-fixture-expansion-report.schema.json": SyntheticFixtureExpansionReport,
    "synthetic-fixture-depth-dimension.schema.json": SyntheticFixtureDepthDimension,
    "synthetic-fixture-depth-family-summary.schema.json": SyntheticFixtureDepthFamilySummary,
    "synthetic-fixture-depth-audit-report.schema.json": SyntheticFixtureDepthAuditReport,
    "rust-ingestion-readiness-report.schema.json": RustIngestionReadinessReport,
    "rust-transition-policy.schema.json": RustTransitionPolicy,
    "segment.schema.json": Segment,
    "effective-context.schema.json": EffectiveContext,
    "party-candidate.schema.json": PartyCandidate,
    "contract-state-dependency.schema.json": ContractStateDependency,
    "contract-state-report.schema.json": ContractStateReport,
    "context-boundary-report.schema.json": ContextBoundaryReport,
    "budget-driver-label.schema.json": BudgetDriverLabel,
    "conflict-seed-label.schema.json": ConflictSeedLabel,
    "courtlistener-dataset-manifest.schema.json": CourtListenerDatasetManifest,
    "courtlistener-dataset-strategy-check.schema.json": CourtListenerDatasetStrategyCheck,
    "courtlistener-dataset-strategy-report.schema.json": CourtListenerDatasetStrategyReport,
    "courtlistener-docket-entry.schema.json": CourtListenerDocketEntry,
    "courtlistener-docket-snapshot.schema.json": CourtListenerDocketSnapshot,
    "courtlistener-fixture-audit-check.schema.json": CourtListenerFixtureAuditCheck,
    "courtlistener-fixture-audit-report.schema.json": CourtListenerFixtureAuditReport,
    "courtlistener-label-source-ref.schema.json": CourtListenerLabelSourceRef,
    "courtlistener-snapshot-document.schema.json": CourtListenerSnapshotDocument,
    "courtlistener-snapshot-segment.schema.json": CourtListenerSnapshotSegment,
    "labor-employment-budget-fact-source.schema.json": LaborEmploymentBudgetFactSource,
    "labor-employment-budget-fact-finding.schema.json": LaborEmploymentBudgetFactFinding,
    "labor-employment-budget-fact-gap.schema.json": LaborEmploymentBudgetFactGap,
    "labor-employment-budget-fact-audit-check.schema.json": (LaborEmploymentBudgetFactAuditCheck),
    "labor-employment-budget-fact-audit-report.schema.json": (LaborEmploymentBudgetFactAuditReport),
    "data-scope-gate-report.schema.json": DataScopeGateReport,
    "public-source-methodology-source.schema.json": PublicSourceMethodologySource,
    "public-source-methodology-check.schema.json": PublicSourceMethodologyCheck,
    "public-source-methodology-report.schema.json": PublicSourceMethodologyReport,
    "public-synthetic-fixture-conversion-spec.schema.json": (PublicSyntheticFixtureConversionSpec),
    "public-synthetic-fixture-conversion-check.schema.json": (
        PublicSyntheticFixtureConversionCheck
    ),
    "public-synthetic-fixture-conversion-plan.schema.json": (PublicSyntheticFixtureConversionPlan),
    "public-synthetic-fixture-conversion-review-recommendation.schema.json": (
        PublicSyntheticFixtureConversionReviewRecommendation
    ),
    "public-synthetic-fixture-conversion-review-red-team-note.schema.json": (
        PublicSyntheticFixtureConversionReviewRedTeamNote
    ),
    "public-synthetic-fixture-conversion-review-decision-template.schema.json": (
        PublicSyntheticFixtureConversionReviewDecisionTemplate
    ),
    "public-synthetic-fixture-conversion-review-packet.schema.json": (
        PublicSyntheticFixtureConversionReviewPacket
    ),
    "public-synthetic-fixture-conversion-review-record.schema.json": (
        PublicSyntheticFixtureConversionReviewRecord
    ),
    "public-synthetic-fixture-conversion-review-outcome-check.schema.json": (
        PublicSyntheticFixtureConversionReviewOutcomeCheck
    ),
    "public-synthetic-fixture-conversion-review-outcome-report.schema.json": (
        PublicSyntheticFixtureConversionReviewOutcomeReport
    ),
    "public-synthetic-fixture-pr-package-check.schema.json": PublicSyntheticFixturePRPackageCheck,
    "public-synthetic-fixture-pr-package-item.schema.json": PublicSyntheticFixturePRPackageItem,
    "public-synthetic-fixture-pr-package-report.schema.json": (
        PublicSyntheticFixturePRPackageReport
    ),
    "model-adapter-report.schema.json": ModelAdapterReport,
    "evidence-completeness-report.schema.json": EvidenceCompletenessReport,
    "fixture-gold-spec.schema.json": FixtureGoldSpec,
    "fixture-gold-report.schema.json": FixtureGoldReport,
    "intake-preflight-packet.schema.json": IntakePreflightPacket,
    "intake-stage-document-label.schema.json": IntakeStageDocumentLabel,
    "deadline-docketing-guard-report.schema.json": DeadlineDocketingGuardReport,
    "human-confirmation.schema.json": HumanConfirmation,
    "human-gate-status-report.schema.json": HumanGateStatusReport,
    "human-review-outcome-record.schema.json": HumanReviewOutcomeRecord,
    "conflict-seed-packet.schema.json": ConflictSeedPacket,
    "person-timeline-event-label.schema.json": PersonTimelineEventLabel,
    "synthetic-intake-wrapper.schema.json": SyntheticIntakeWrapper,
    "budget-precondition-report.schema.json": BudgetPreconditionReport,
    "budget-form-mapping-report.schema.json": BudgetFormMappingReport,
    "budget-form-template-audit-report.schema.json": BudgetFormTemplateAuditReport,
    "budget-submission-guard-report.schema.json": BudgetSubmissionGuardReport,
    "matter-opening-readiness.schema.json": MatterOpeningReadiness,
    "legal-budget-proposal.schema.json": BudgetProposal,
    "budget-actual-amount.schema.json": BudgetActualAmount,
    "budget-actuals-source.schema.json": BudgetActualsSource,
    "budget-actual-comparison-report.schema.json": BudgetActualComparisonReport,
    "budget-actual-phase-comparison.schema.json": BudgetActualPhaseComparison,
    "budget-actual-code-comparison.schema.json": BudgetActualCodeComparison,
    "budget-actual-variance-driver-candidate.schema.json": (BudgetActualVarianceDriverCandidate),
    "budget-actual-variance-ledger-event.schema.json": BudgetActualVarianceLedgerEvent,
    "budget-actual-variance-ledger-report.schema.json": BudgetActualVarianceLedgerReport,
    "budget-actual-variance-owner-adoption-check.schema.json": (
        BudgetActualVarianceOwnerAdoptionCheck
    ),
    "budget-actual-variance-owner-adoption-packet.schema.json": (
        BudgetActualVarianceOwnerAdoptionPacket
    ),
    "budget-actual-variance-owner-adoption-report.schema.json": (
        BudgetActualVarianceOwnerAdoptionReport
    ),
    "budget-calibration-corpus-artifact.schema.json": BudgetCalibrationCorpusArtifact,
    "budget-calibration-corpus-check.schema.json": BudgetCalibrationCorpusCheck,
    "budget-calibration-corpus-report.schema.json": BudgetCalibrationCorpusReport,
    "budget-calibration-readiness-check.schema.json": BudgetCalibrationReadinessCheck,
    "budget-calibration-readiness-report.schema.json": BudgetCalibrationReadinessReport,
    "budget-change-ledger-event.schema.json": BudgetChangeLedgerEvent,
    "budget-change-ledger-report.schema.json": BudgetChangeLedgerReport,
    "budget-corpus-replay-case.schema.json": BudgetCorpusReplayCase,
    "budget-corpus-replay-case-result.schema.json": BudgetCorpusReplayCaseResult,
    "budget-corpus-replay-check.schema.json": BudgetCorpusReplayCheck,
    "budget-corpus-replay-command.schema.json": BudgetCorpusReplayCommand,
    "budget-corpus-replay-command-result.schema.json": BudgetCorpusReplayCommandResult,
    "budget-corpus-replay-execution-check.schema.json": BudgetCorpusReplayExecutionCheck,
    "budget-corpus-replay-execution-report.schema.json": (BudgetCorpusReplayExecutionReport),
    "budget-corpus-replay-output-check.schema.json": BudgetCorpusReplayOutputCheck,
    "budget-corpus-replay-plan.schema.json": BudgetCorpusReplayPlan,
    "budget-corpus-replay-review-decision-template.schema.json": (
        BudgetCorpusReplayReviewDecisionTemplate
    ),
    "budget-corpus-replay-review-outcome-check.schema.json": (BudgetCorpusReplayReviewOutcomeCheck),
    "budget-corpus-replay-review-outcome-record.schema.json": (
        BudgetCorpusReplayReviewOutcomeRecord
    ),
    "budget-corpus-replay-review-outcome-report.schema.json": (
        BudgetCorpusReplayReviewOutcomeReport
    ),
    "budget-corpus-replay-review-packet.schema.json": BudgetCorpusReplayReviewPacket,
    "budget-corpus-replay-review-recommendation.schema.json": (
        BudgetCorpusReplayReviewRecommendation
    ),
    "budget-corpus-replay-review-red-team-note.schema.json": (BudgetCorpusReplayReviewRedTeamNote),
    "budget-fixture-binding-candidate.schema.json": BudgetFixtureBindingCandidate,
    "budget-fixture-binding-check.schema.json": BudgetFixtureBindingCheck,
    "budget-fixture-binding-candidate-report.schema.json": BudgetFixtureBindingCandidateReport,
    "budget-fixture-binding-handoff-item.schema.json": BudgetFixtureBindingHandoffItem,
    "budget-fixture-binding-handoff-report.schema.json": BudgetFixtureBindingHandoffReport,
    "budget-fixture-update-review-check.schema.json": BudgetFixtureUpdateReviewCheck,
    "budget-fixture-update-review-record.schema.json": BudgetFixtureUpdateReviewRecord,
    "budget-fixture-update-review-report.schema.json": BudgetFixtureUpdateReviewReport,
    "budget-fixture-update-pr-package-check.schema.json": BudgetFixtureUpdatePRPackageCheck,
    "budget-fixture-update-pr-package-item.schema.json": BudgetFixtureUpdatePRPackageItem,
    "budget-fixture-update-pr-package-report.schema.json": (BudgetFixtureUpdatePRPackageReport),
    "budget-review-change.schema.json": BudgetReviewChange,
    "budget-review-change-record.schema.json": BudgetReviewChangeRecord,
    "budget-phase-budget-snapshot.schema.json": BudgetPhaseBudgetSnapshot,
    "budget-code-budget-snapshot.schema.json": BudgetCodeBudgetSnapshot,
    "budget-revision-delta.schema.json": BudgetRevisionDelta,
    "budget-revision-report.schema.json": BudgetRevisionReport,
    "budget-driver-effect.schema.json": BudgetDriverEffect,
    "budget-driver-profile-summary.schema.json": BudgetDriverProfileSummary,
    "budget-guideline-flag.schema.json": BudgetGuidelineFlag,
    "budget-lake-evidence-artifact.schema.json": BudgetLakeEvidenceArtifact,
    "budget-lake-admission-bundle-check.schema.json": BudgetLakeAdmissionBundleCheck,
    "budget-lake-admission-bundle-report.schema.json": BudgetLakeAdmissionBundleReport,
    "budget-lifecycle-audit-check.schema.json": BudgetLifecycleAuditCheck,
    "budget-lifecycle-financial-summary.schema.json": BudgetLifecycleFinancialSummary,
    "budget-lifecycle-audit-report.schema.json": BudgetLifecycleAuditReport,
    "budget-human-review-packet-check.schema.json": BudgetHumanReviewPacketCheck,
    "budget-human-review-recommendation.schema.json": BudgetHumanReviewRecommendation,
    "budget-human-review-red-team-note.schema.json": BudgetHumanReviewRedTeamNote,
    "budget-human-review-decision-template.schema.json": BudgetHumanReviewDecisionTemplate,
    "budget-human-review-packet.schema.json": BudgetHumanReviewPacket,
    "budget-human-review-outcome-decision.schema.json": BudgetHumanReviewOutcomeDecision,
    "budget-human-review-outcome-record.schema.json": BudgetHumanReviewOutcomeRecord,
    "budget-human-review-outcome-check.schema.json": BudgetHumanReviewOutcomeCheck,
    "budget-human-review-outcome-report.schema.json": BudgetHumanReviewOutcomeReport,
    "budget-human-review-outcome-owner-adoption-check.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionCheck
    ),
    "budget-human-review-outcome-owner-adoption-packet.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionPacket
    ),
    "budget-human-review-outcome-owner-adoption-report.schema.json": (
        BudgetHumanReviewOutcomeOwnerAdoptionReport
    ),
    "budget-lifecycle-owner-adoption-packet.schema.json": (BudgetLifecycleOwnerAdoptionPacket),
    "budget-lifecycle-owner-adoption-report.schema.json": (BudgetLifecycleOwnerAdoptionReport),
    "carrier-compliant-projection.schema.json": CarrierCompliantProjection,
    "carrier-compliant-projection-basis.schema.json": CarrierCompliantProjectionBasis,
    "carrier-compliant-leverage-summary.schema.json": CarrierCompliantLeverageSummary,
    "carrier-compliant-projection-line.schema.json": CarrierCompliantProjectionLine,
    "carrier-preapproval-requirement.schema.json": CarrierPreapprovalRequirement,
    "carrier-preapproval-report.schema.json": CarrierPreapprovalReport,
    "named-timekeeper-rate.schema.json": NamedTimekeeperRate,
    "budget-scenario-set.schema.json": BudgetScenarioSet,
    "budget-support-item.schema.json": BudgetSupportItem,
    "carrier-expected-response.schema.json": CarrierExpectedResponse,
    "carrier-rejection-source-ref.schema.json": CarrierRejectionSourceRef,
    "carrier-rejection-notice.schema.json": CarrierRejectionNotice,
    "carrier-appeal-result.schema.json": CarrierAppealResult,
    "carrier-rejection-capture-source-bundle.schema.json": CarrierRejectionCaptureSourceBundle,
    "carrier-rejection-decision-ledger-event.schema.json": (CarrierRejectionDecisionLedgerEvent),
    "carrier-rejection-decision-ledger-report.schema.json": (CarrierRejectionDecisionLedgerReport),
    "carrier-rejection-remediation-case.schema.json": CarrierRejectionRemediationCase,
    "carrier-response-reconciliation-report.schema.json": CarrierResponseReconciliationReport,
    "carrier-rejection-review-recommendation.schema.json": (CarrierRejectionReviewRecommendation),
    "carrier-rejection-review-red-team-note.schema.json": CarrierRejectionReviewRedTeamNote,
    "carrier-rejection-review-decision-template.schema.json": (
        CarrierRejectionReviewDecisionTemplate
    ),
    "carrier-rejection-review-packet.schema.json": CarrierRejectionReviewPacket,
    "carrier-rejection-learning-proposal.schema.json": CarrierRejectionLearningProposal,
    "carrier-rejection-learning-report.schema.json": CarrierRejectionLearningReport,
    "carrier-rejection-lake-admission-record-spec.schema.json": (
        CarrierRejectionLakeAdmissionRecordSpec
    ),
    "carrier-rejection-lake-admission-check.schema.json": CarrierRejectionLakeAdmissionCheck,
    "carrier-rejection-lake-admission-proposal.schema.json": (
        CarrierRejectionLakeAdmissionProposal
    ),
    "carrier-rejection-orchestrator-connector-channel.schema.json": (
        CarrierRejectionOrchestratorConnectorChannel
    ),
    "carrier-rejection-orchestrator-workflow-step.schema.json": (
        CarrierRejectionOrchestratorWorkflowStep
    ),
    "carrier-rejection-orchestrator-interface-draft.schema.json": (
        CarrierRejectionOrchestratorInterfaceDraft
    ),
    "orchestrator-owner-review-source-ref.schema.json": OrchestratorOwnerReviewSourceRef,
    "orchestrator-owner-review-human-confirmation.schema.json": (
        OrchestratorOwnerReviewHumanConfirmation
    ),
    "orchestrator-owner-review-budget-preconditions.schema.json": (
        OrchestratorOwnerReviewBudgetPreconditions
    ),
    "orchestrator-owner-review-budget-actual-line.schema.json": (
        OrchestratorOwnerReviewBudgetActualLine
    ),
    "orchestrator-owner-review-carrier-appeal.schema.json": OrchestratorOwnerReviewCarrierAppeal,
    "orchestrator-owner-review-carrier-appeal-result.schema.json": (
        OrchestratorOwnerReviewCarrierAppealResult
    ),
    "orchestrator-owner-review-carrier-rejection-notice.schema.json": (
        OrchestratorOwnerReviewCarrierRejectionNotice
    ),
    "orchestrator-owner-review-request.schema.json": OrchestratorOwnerReviewRequest,
    "carrier-rejection-roadmap-slice-status.schema.json": (CarrierRejectionRoadmapSliceStatus),
    "carrier-rejection-roadmap-audit-check.schema.json": CarrierRejectionRoadmapAuditCheck,
    "carrier-rejection-roadmap-audit-report.schema.json": (CarrierRejectionRoadmapAuditReport),
    "evidence-graph.schema.json": EvidenceGraph,
    "run-ledger-event.schema.json": RunEvent,
    "run-ledger-integrity-report.schema.json": RunLedgerIntegrityReport,
    "exception-lake-candidate.schema.json": ExceptionLakeCandidate,
    "exception-lake-readiness-report.schema.json": ExceptionLakeReadinessReport,
    "exception-lake-handoff-manifest.schema.json": ExceptionLakeHandoffManifest,
    "exception-lake-mapping-package.schema.json": ExceptionLakeMappingPackage,
    "exception-lake-mapping-rule.schema.json": ExceptionLakeMappingRule,
    "review-package-manifest.schema.json": ReviewPackageManifest,
    "review-package-completeness-report.schema.json": ReviewPackageCompletenessReport,
    "reviewed-learning-gate-candidate.schema.json": ReviewedLearningGateCandidate,
    "reviewed-learning-gate-check.schema.json": ReviewedLearningGateCheck,
    "reviewed-learning-gate-report.schema.json": ReviewedLearningGateReport,
    "learning-shadow-eval-case.schema.json": LearningShadowEvalCase,
    "learning-shadow-eval-plan.schema.json": LearningShadowEvalPlan,
    "learning-promotion-readiness-check.schema.json": LearningPromotionReadinessCheck,
    "learning-promotion-readiness-report.schema.json": LearningPromotionReadinessReport,
    "learning-proposed-change-red-team-note.schema.json": (LearningProposedChangeRedTeamNote),
    "learning-proposed-change-artifact.schema.json": LearningProposedChangeArtifact,
    "learning-proposed-change-set.schema.json": LearningProposedChangeSet,
    "learning-shadow-eval-fixture-result.schema.json": LearningShadowEvalFixtureResult,
    "learning-shadow-eval-fixture-review-item.schema.json": (LearningShadowEvalFixtureReviewItem),
    "learning-shadow-eval-fixture-review-record.schema.json": (
        LearningShadowEvalFixtureReviewRecord
    ),
    "learning-shadow-eval-fixture-evidence-check.schema.json": (
        LearningShadowEvalFixtureEvidenceCheck
    ),
    "learning-shadow-eval-fixture-evidence-report.schema.json": (
        LearningShadowEvalFixtureEvidenceReport
    ),
    "learning-shadow-eval-result.schema.json": LearningShadowEvalResult,
    "learning-shadow-eval-result-report.schema.json": LearningShadowEvalResultReport,
    "learning-owner-handoff-item.schema.json": LearningOwnerHandoffItem,
    "learning-owner-handoff-package.schema.json": LearningOwnerHandoffPackage,
    "learning-owner-handoff-report.schema.json": LearningOwnerHandoffReport,
    "starter-release-audit-report.schema.json": StarterReleaseAuditReport,
    "safety-gate-report.schema.json": SafetyGateReport,
}


def main() -> int:
    target = ROOT / "schemas"
    target.mkdir(exist_ok=True)
    for filename, model in MODELS.items():
        (target / filename).write_text(
            json.dumps(model.model_json_schema(), indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    print(f"exported {len(MODELS)} schemas to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
