#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
rm -rf .lawfirm-os-intake/smoke
python -m lawfirm_os_intake demo \
  --input examples/synthetic/inbound/north-star-messy-intake.json \
  --practice-profile context/synthetic-profiles/insurance-defense.yaml \
  --confirmation-template examples/synthetic/confirmations/north-star-messy-intake.confirmation-template.json \
  --out-dir .lawfirm-os-intake/smoke

preflight_dir="$(find .lawfirm-os-intake/smoke/preflight -mindepth 1 -maxdepth 1 -type d | head -n 1)"
test -n "$preflight_dir"
test -s "$preflight_dir/contract_state_report.json"
test -s "$preflight_dir/ingestion_result.json"
test -s "$preflight_dir/rust_ingestion_readiness_report.json"
test -s "$preflight_dir/intake_review_form.md"
grep -q '"status": "passed"' "$preflight_dir/contract_state_report.json"
grep -q '"parity_contract": "rust_ready_ingestion_v0_1"' "$preflight_dir/ingestion_result.json"
grep -q '"status": "passed"' "$preflight_dir/rust_ingestion_readiness_report.json"
grep -q '"rust_replacement_allowed": false' "$preflight_dir/rust_ingestion_readiness_report.json"
test -s "$preflight_dir/exception_lake_candidates.jsonl"
test -s "$preflight_dir/exception_lake_readiness_report.json"
grep -q "prompt_injection_source_content" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "source_missing" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "duplicate_source_detected" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q '"status": "passed"' "$preflight_dir/exception_lake_readiness_report.json"
grep -q "duplicate_of=syn-northstar-email-001" "$preflight_dir/intake_review_form.md"
grep -q "attachments=complaint.pdf, medical-chronology.pdf" "$preflight_dir/intake_review_form.md"
grep -q "## Review Outcome Handling" "$preflight_dir/intake_review_form.md"
grep -q "confirmed -> budget_precondition_gate" "$preflight_dir/intake_review_form.md"
grep -q "append_or_supersede_only" "$preflight_dir/intake_review_form.md"
test -s ".lawfirm-os-intake/smoke/budget/exception_lake_candidates.jsonl"
test -s ".lawfirm-os-intake/smoke/budget/exception_lake_readiness_report.json"
grep -q '"admission_state": "dry_run_not_admitted"' ".lawfirm-os-intake/smoke/budget/exception_lake_readiness_report.json"
test -s ".lawfirm-os-intake/smoke/budget/budget_precondition_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/budget_precondition_report.json"
test -s ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "## Budget Lines" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "rate source: synthetic_profile" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "## Submission Boundary" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "Client/carrier submission authorized: False" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
test -s ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
test -s ".lawfirm-os-intake/smoke/budget/review_package_manifest.json"
test -s ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
test -s ".lawfirm-os-intake/smoke/budget/safety_gate_report.json"
grep -q "Status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Authority And Preconditions" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Contract state status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Budget precondition status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Source Inventory" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "syn-northstar-attachment-missing-001" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Human confirmation decision evidence:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "] sha=sha256:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Candidate Alternatives" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Required Human Gates" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Budget Lines" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Exception Lake Readiness" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
exception_candidate_details="$(awk '/### Exception Candidate Details/{flag=1;next}/## Safety Gate/{flag=0}flag' \
  ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md")"
grep -q "] sha=sha256:" <<< "$exception_candidate_details"
grep -q "raw_payload_included=False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Evidence Graph Summary" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "supports_conflict_search_term=" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Run Ledger Summary" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "budget step 4: conflict_seed_and_budget_proposal_built" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "linked_review_forms_complete" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "review_package_completeness_report.json" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "blocked_pending_conflicts_and_engagement" ".lawfirm-os-intake/smoke/budget/safety_gate_report.json"
