#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
rm -rf .lawfirm-os-intake/smoke
python -m lawfirm_os_intake demo \
  --input examples/synthetic/inbound/north-star-messy-intake.json \
  --practice-profile context/synthetic-profiles/insurance-defense.yaml \
  --confirmation-template examples/synthetic/confirmations/north-star-messy-intake.confirmation-template.json \
  --fixture-gold examples/synthetic/gold/north-star-messy-intake.fixture-gold.json \
  --out-dir .lawfirm-os-intake/smoke

preflight_dir="$(find .lawfirm-os-intake/smoke/preflight -mindepth 1 -maxdepth 1 -type d | head -n 1)"
test -n "$preflight_dir"
test -s "$preflight_dir/contract_state_report.json"
test -s "$preflight_dir/ingestion_result.json"
test -s "$preflight_dir/ingestion_volume_profile.json"
test -s "$preflight_dir/rust_ingestion_readiness_report.json"
test -s "$preflight_dir/intake_review_form.md"
test -s "$preflight_dir/deadline_docketing_guard_report.json"
grep -q '"status": "passed"' "$preflight_dir/contract_state_report.json"
grep -q '"parity_contract": "rust_ready_ingestion_v0_1"' "$preflight_dir/ingestion_result.json"
grep -q '"decision": "keep_python_reference"' "$preflight_dir/ingestion_volume_profile.json"
grep -q '"rust_replacement_allowed": false' "$preflight_dir/ingestion_volume_profile.json"
grep -q '"required_performance_profile_dimensions"' "$preflight_dir/ingestion_volume_profile.json"
grep -q '"candidate_rust_hot_path_scope"' "$preflight_dir/ingestion_volume_profile.json"
grep -q '"status": "passed"' "$preflight_dir/rust_ingestion_readiness_report.json"
grep -q '"rust_replacement_allowed": false' "$preflight_dir/rust_ingestion_readiness_report.json"
grep -q '"status": "passed"' "$preflight_dir/deadline_docketing_guard_report.json"
grep -q '"docketing_action_performed": false' "$preflight_dir/deadline_docketing_guard_report.json"
grep -q '"proposed_next_gate": "human_deadline_review"' "$preflight_dir/deadline_docketing_guard_report.json"
test -s "$preflight_dir/exception_lake_candidates.jsonl"
test -s "$preflight_dir/exception_lake_readiness_report.json"
test -s "$preflight_dir/exception_lake_handoff_manifest.json"
test -s "$preflight_dir/run_ledger_integrity_report.json"
test -s "$preflight_dir/fixture_gold_report.json"
grep -q '"status": "passed"' "$preflight_dir/fixture_gold_report.json"
grep -q '"top_three_matter_family_recall"' "$preflight_dir/fixture_gold_report.json"
grep -q "prompt_injection_source_content" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "prohibited_transition_attempted_conflicts_cleared" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "prohibited_transition_attempted_deadline_docketed" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "prohibited_transition_attempted_matter_opened" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "critic_role_candidates_ambiguous" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "source_missing" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q "duplicate_source_detected" "$preflight_dir/exception_lake_candidates.jsonl"
grep -q '"status": "passed"' "$preflight_dir/exception_lake_readiness_report.json"
grep -q '"status": "dry_run_ready_not_admitted"' "$preflight_dir/exception_lake_handoff_manifest.json"
grep -q '"sqlite_write_performed": false' "$preflight_dir/exception_lake_handoff_manifest.json"
grep -q '"status": "passed"' "$preflight_dir/run_ledger_integrity_report.json"
grep -q '"stage": "preflight"' "$preflight_dir/run_ledger_integrity_report.json"
grep -q "duplicate_of=syn-northstar-email-001" "$preflight_dir/intake_review_form.md"
grep -q "attachments=complaint.pdf, medical-chronology.pdf" "$preflight_dir/intake_review_form.md"
grep -q "## Review Outcome Handling" "$preflight_dir/intake_review_form.md"
grep -q "confirmed -> budget_precondition_gate" "$preflight_dir/intake_review_form.md"
grep -q "append_or_supersede_only" "$preflight_dir/intake_review_form.md"
test -s ".lawfirm-os-intake/smoke/budget/exception_lake_candidates.jsonl"
test -s ".lawfirm-os-intake/smoke/budget/exception_lake_readiness_report.json"
test -s ".lawfirm-os-intake/smoke/budget/exception_lake_handoff_manifest.json"
test -s ".lawfirm-os-intake/smoke/budget/run_ledger_integrity_report.json"
grep -q '"admission_state": "dry_run_not_admitted"' ".lawfirm-os-intake/smoke/budget/exception_lake_readiness_report.json"
grep -q '"stage": "budget_combined"' ".lawfirm-os-intake/smoke/budget/exception_lake_handoff_manifest.json"
grep -q '"sqlite_write_performed": false' ".lawfirm-os-intake/smoke/budget/exception_lake_handoff_manifest.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/run_ledger_integrity_report.json"
grep -q '"stage": "budget_success"' ".lawfirm-os-intake/smoke/budget/run_ledger_integrity_report.json"
test -s ".lawfirm-os-intake/smoke/budget/budget_precondition_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/budget_precondition_report.json"
test -s ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "## Budget Lines" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "rate source: synthetic_profile" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "## Submission Boundary" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
grep -q "Client/carrier submission authorized: False" ".lawfirm-os-intake/smoke/budget/legal_budget_review_form.md"
test -s ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
test -s ".lawfirm-os-intake/smoke/budget/review_package_manifest.json"
test -s ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
test -s ".lawfirm-os-intake/smoke/budget/fixture_gold_report.json"
test -s ".lawfirm-os-intake/smoke/budget/safety_gate_report.json"
test -s ".lawfirm-os-intake/smoke/budget/budget_submission_guard_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/fixture_gold_report.json"
grep -q '"final_boundary"' ".lawfirm-os-intake/smoke/budget/fixture_gold_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/budget_submission_guard_report.json"
grep -q '"client_submission_performed": false' ".lawfirm-os-intake/smoke/budget/budget_submission_guard_report.json"
grep -q '"billing_handoff_performed": false' ".lawfirm-os-intake/smoke/budget/budget_submission_guard_report.json"
grep -q "Status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Authority And Preconditions" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Contract state status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Budget precondition status: passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Source Inventory" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Ingestion volume profile:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Required performance profile dimensions:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Candidate Rust hot path scope:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "syn-northstar-attachment-missing-001" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Human confirmation decision evidence:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "] sha=sha256:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Candidate Alternatives" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Required Human Gates" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
test -s ".lawfirm-os-intake/smoke/budget/human_gate_status_report.json"
grep -q '"status": "pending_human_gates"' ".lawfirm-os-intake/smoke/budget/human_gate_status_report.json"
grep -q '"gate_id": "human_budget_review"' ".lawfirm-os-intake/smoke/budget/human_gate_status_report.json"
grep -q "Human gate status report:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "human_intake_confirmation: completed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "human_budget_review: pending" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Deadline docketing guard report:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Docketing action performed: False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Deadline proposed next gate: human_deadline_review" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Budget submission guard report:" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Client submission performed: False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "Billing handoff performed: False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Budget Lines" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Exception Lake Readiness" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Exception Lake Handoff" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "SQLite write performed: False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "budget_unknowns_require_review: class=workflow_escalation" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
exception_candidate_details="$(awk '/### Exception Candidate Details/{flag=1;next}/## Safety Gate/{flag=0}flag' \
  ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md")"
grep -q "] sha=sha256:" <<< "$exception_candidate_details"
grep -q "raw_payload_included=False" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Evidence Graph Summary" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "supports_conflict_search_term=" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "blocker detail: conflicts_not_cleared" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "blocker detail: budget_review_not_completed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "structured_ref=workflow/intake-to-budget.workflow.yaml#conflicts_review" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "prohibited action detail: do_not_submit_budget" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "workflow/prohibited-transitions.yaml#budget_proposal_ready->budget_submitted" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "## Run Ledger Summary" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "### Run Ledger Integrity" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "budget_success: status=passed" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "budget step 4: conflict_seed_and_budget_proposal_built" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "linked_review_forms_complete" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "linked_review_forms_preserve_evidence_and_boundaries" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "preflight_ingestion_volume_profile" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "budget_exception_lake_handoff_manifest" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "run_ledger_integrity_reports_passed" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "readiness_blocker_details_rendered" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "human_gate_status_report_complete" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "deadline_docketing_guard_report_complete" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "preflight_deadline_docketing_guard_report" ".lawfirm-os-intake/smoke/budget/review_package_manifest.json"
grep -q "budget_submission_guard_report_complete" ".lawfirm-os-intake/smoke/budget/review_package_completeness_report.json"
grep -q "budget_submission_guard_report" ".lawfirm-os-intake/smoke/budget/review_package_manifest.json"
grep -q "review_package_completeness_report.json" ".lawfirm-os-intake/smoke/budget/matter_opening_review_package.md"
grep -q "blocked_pending_conflicts_and_engagement" ".lawfirm-os-intake/smoke/budget/safety_gate_report.json"
python scripts/audit_starter_release.py --demo-dir .lawfirm-os-intake/smoke
test -s ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "north_star_source_coverage_exercised" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "north_star_candidate_surface_complete" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "evidence_graph_covers_intake_to_budget_deliverables" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "human_review_package_tells_complete_north_star_story" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "budget_boundary_and_math_hold" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "deadline_and_budget_guard_reports_hold" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
grep -q "exception_lake_candidates_are_dry_run_and_expected" ".lawfirm-os-intake/smoke/budget/starter_release_audit_report.json"
python scripts/audit_blocked_budget_attempt.py \
  --preflight-packet "$preflight_dir/intake_preflight_packet.json" \
  --confirmation-template examples/synthetic/confirmations/north-star-messy-intake.confirmation-template.json \
  --practice-profile context/synthetic-profiles/insurance-defense.yaml \
  --out-dir .lawfirm-os-intake/smoke/blocked-budget
test -s ".lawfirm-os-intake/smoke/blocked-budget/blocked_budget_attempt_audit_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/blocked-budget/blocked_budget_attempt_audit_report.json"
grep -q "no_prohibited_budget_outputs_emitted" ".lawfirm-os-intake/smoke/blocked-budget/blocked_budget_attempt_audit_report.json"
grep -q "budget_blocked_before_human_confirmation" ".lawfirm-os-intake/smoke/blocked-budget/blocked_budget_attempt_audit_report.json"
test -s ".lawfirm-os-intake/smoke/blocked-budget/budget/exception_lake_handoff_manifest.json"
test -s ".lawfirm-os-intake/smoke/blocked-budget/budget/run_ledger_integrity_report.json"
grep -q '"stage": "budget_precondition_blocked"' ".lawfirm-os-intake/smoke/blocked-budget/budget/exception_lake_handoff_manifest.json"
grep -q '"sqlite_write_performed": false' ".lawfirm-os-intake/smoke/blocked-budget/budget/exception_lake_handoff_manifest.json"
grep -q '"stage": "budget_precondition_blocked"' ".lawfirm-os-intake/smoke/blocked-budget/budget/run_ledger_integrity_report.json"
grep -q '"terminal_status": "blocked"' ".lawfirm-os-intake/smoke/blocked-budget/budget/run_ledger_integrity_report.json"
test ! -e ".lawfirm-os-intake/smoke/blocked-budget/budget/legal_budget_proposal.json"
test ! -e ".lawfirm-os-intake/smoke/blocked-budget/budget/conflict_search_seed_packet.json"
python scripts/audit_context_counterfactual.py \
  --input examples/synthetic/inbound/help-email.json \
  --baseline-profile context/synthetic-profiles/insurance-defense.yaml \
  --comparison-profile context/synthetic-profiles/plaintiff-personal-injury.yaml \
  --out-dir .lawfirm-os-intake/smoke/context-counterfactual
test -s ".lawfirm-os-intake/smoke/context-counterfactual/context_counterfactual_audit_report.json"
grep -q '"status": "passed"' ".lawfirm-os-intake/smoke/context-counterfactual/context_counterfactual_audit_report.json"
grep -q "observed_evidence_refs_stable" ".lawfirm-os-intake/smoke/context-counterfactual/context_counterfactual_audit_report.json"
grep -q "context_only_candidate_not_observed_fact" ".lawfirm-os-intake/smoke/context-counterfactual/context_counterfactual_audit_report.json"
grep -q "practice_context_changes_ranking" ".lawfirm-os-intake/smoke/context-counterfactual/context_counterfactual_audit_report.json"
