from __future__ import annotations

from pathlib import Path

from .models import (
    CrossRepoOwnerAdoptionPacket,
    CrossRepoOwnerAdoptionReport,
    CrossRepoOwnerIssueDraft,
    CrossRepoOwnerIssueDraftReport,
)
from .util import append_jsonl, digest_text, load_json, now_iso, write_json


CROSS_REPO_OWNER_ISSUE_DRAFT_REPORT_FILENAME = "cross_repo_owner_issue_draft_report.json"
CROSS_REPO_OWNER_ISSUE_DRAFT_NOTES_FILENAME = "cross_repo_owner_issue_draft_report.md"
CROSS_REPO_OWNER_ISSUE_DRAFTS_FILENAME = "cross_repo_owner_issue_drafts.jsonl"
CROSS_REPO_OWNER_ISSUE_DRAFT_DIRNAME = "owner_issue_drafts"

REQUIRED_NEXT_GATES = [
    "human_pr_review_decision",
    "manual_owner_issue_creation_if_desired",
    "owning_repo_triage",
    "owner_repo_implementation_pr_if_accepted",
    "cross_repo_contract_validation_after_owner_changes",
]


def _stable_id(prefix: str, value: str) -> str:
    return f"{prefix}_{digest_text(value).split(':', maxsplit=1)[1][:20]}"


def _owner_slug(owner: str) -> str:
    return owner.lower().replace("lawfirm-os-", "").replace("_", "-")


def _labels(packet: CrossRepoOwnerAdoptionPacket) -> list[str]:
    owner_label = _owner_slug(packet.target_repo)
    return [
        "lawfirm-os-intake-handoff",
        "candidate-only",
        owner_label,
        packet.authority_plane,
    ]


def _issue_title(packet: CrossRepoOwnerAdoptionPacket) -> str:
    return f"Review intake-to-budget candidate adoption package for {packet.target_repo}"


def _proposal_summary(packet: CrossRepoOwnerAdoptionPacket) -> list[str]:
    if not packet.proposals:
        return ["- none"]
    return [
        f"- `{proposal.proposal_id}` ({proposal.proposal_type}): {proposal.summary}"
        for proposal in packet.proposals
    ]


def _issue_body(*, packet: CrossRepoOwnerAdoptionPacket, packet_ref: str) -> str:
    status_note = (
        "This draft is ready for a human to create manually."
        if packet.status == "ready_for_owner_review"
        else (
            "This draft is blocked until the promotion-package audit is repaired."
            if packet.status == "blocked_by_promotion_package_audit"
            else "This draft is blocked until the intake PR readiness evidence is repaired."
        )
    )
    lines = [
        "## Summary",
        "",
        status_note,
        "",
        "This is a local draft generated by `LawFirm-os-intake`. It is candidate-only "
        "handoff text for the owning repo. It does not create this issue, open a PR, "
        "write this repo, promote canon, admit Lake records, or apply learning.",
        "",
        "## Source Evidence",
        "",
        f"- Owner adoption packet: `{packet_ref}`",
        f"- Promotion package: `{packet.source_promotion_package_ref}`",
        f"- Promotion package audit: `{packet.source_promotion_package_audit_report_ref}`",
        f"- Readiness audit: `{packet.source_readiness_audit_report_ref}`",
        f"- PR review checklist: `{packet.source_pr_review_checklist_ref}`",
        "",
        "## Candidate Proposals",
        "",
        *_proposal_summary(packet),
        "",
        "## Required Owner Actions",
        "",
        *(f"- [ ] {action}" for action in packet.required_owner_actions),
        "",
        "## Acceptance Checks",
        "",
        *(f"- [ ] {check}" for check in packet.acceptance_checks),
        "",
        "## Red-Team Notes",
        "",
        *(f"- {note}" for note in packet.red_team_notes),
        "",
        "## Required Next Gates",
        "",
        *(f"- {gate}" for gate in packet.required_next_gates),
        "",
        "## Boundary",
        "",
        "- Intake did not create this issue.",
        "- Intake did not write a sibling repo.",
        "- Intake did not promote canonical schemas, event classes, route IDs, or skill trust records.",
        "- Intake did not admit Lake records or write SQLite.",
        "- Intake did not implement production connectors or external writes.",
        "- Intake did not apply learning or mutate baselines.",
        "",
    ]
    return "\n".join(lines)


def _draft_for_packet(
    *,
    packet: CrossRepoOwnerAdoptionPacket,
    packet_ref: str,
) -> CrossRepoOwnerIssueDraft:
    ready = packet.status == "ready_for_owner_review"
    return CrossRepoOwnerIssueDraft(
        issue_draft_id=_stable_id(
            "ownerissuedraft",
            f"{packet.adoption_packet_id}|{packet.target_repo}",
        ),
        target_repo=packet.target_repo,
        source_owner_adoption_packet_id=packet.adoption_packet_id,
        source_owner_adoption_packet_ref=packet_ref,
        source_owner_adoption_packet_status=packet.status,
        status=("ready_for_manual_issue_creation" if ready else "blocked_by_owner_adoption_packet"),
        suggested_title=_issue_title(packet),
        suggested_labels=_labels(packet),
        issue_body_markdown=_issue_body(packet=packet, packet_ref=packet_ref),
        proposal_count=packet.proposal_count,
        proposal_ids=[proposal.proposal_id for proposal in packet.proposals],
        required_owner_actions=packet.required_owner_actions,
        acceptance_checks=packet.acceptance_checks,
        red_team_notes=packet.red_team_notes,
        required_next_gates=REQUIRED_NEXT_GATES,
    )


def _load_packet(ref: str | Path) -> CrossRepoOwnerAdoptionPacket:
    return CrossRepoOwnerAdoptionPacket.model_validate(load_json(ref))


def build_cross_repo_owner_issue_drafts(
    *,
    owner_adoption_report: CrossRepoOwnerAdoptionReport,
    owner_adoption_report_ref: str,
    packets: list[CrossRepoOwnerAdoptionPacket],
    packet_refs: list[str],
    draft_output_refs: list[str],
) -> CrossRepoOwnerIssueDraftReport:
    drafts = [
        _draft_for_packet(packet=packet, packet_ref=packet_ref)
        for packet, packet_ref in zip(packets, packet_refs, strict=True)
    ]
    ready_count = sum(1 for draft in drafts if draft.status == "ready_for_manual_issue_creation")
    blocked_count = len(drafts) - ready_count
    return CrossRepoOwnerIssueDraftReport(
        issue_draft_report_id=_stable_id(
            "ownerissuedraftreport",
            f"{owner_adoption_report.owner_adoption_report_id}|{owner_adoption_report_ref}",
        ),
        status=(
            "issue_drafts_ready_for_manual_creation"
            if blocked_count == 0
            else "blocked_by_owner_adoption"
        ),
        source_owner_adoption_report_id=owner_adoption_report.owner_adoption_report_id,
        source_owner_adoption_report_ref=owner_adoption_report_ref,
        source_owner_adoption_status=owner_adoption_report.status,
        draft_count=len(drafts),
        ready_draft_count=ready_count,
        blocked_draft_count=blocked_count,
        target_repos=owner_adoption_report.target_repos,
        drafts=drafts,
        draft_output_refs=draft_output_refs,
        required_next_gates=REQUIRED_NEXT_GATES,
        generated_at=now_iso(),
    )


def render_cross_repo_owner_issue_draft_report(
    report: CrossRepoOwnerIssueDraftReport,
) -> str:
    lines = [
        "# Cross-Repo Owner Issue Draft Report",
        "",
        f"**Report ID:** {report.issue_draft_report_id}",
        f"**Status:** {report.status}",
        f"**Source owner adoption report:** `{report.source_owner_adoption_report_ref}`",
        f"**Ready drafts:** {report.ready_draft_count}",
        f"**Blocked drafts:** {report.blocked_draft_count}",
        "",
        "## Drafts",
        "",
    ]
    for draft, output_ref in zip(report.drafts, report.draft_output_refs, strict=True):
        lines.extend(
            [
                f"### {draft.target_repo}",
                "",
                f"- Status: {draft.status}",
                f"- Suggested title: {draft.suggested_title}",
                f"- Suggested labels: {', '.join(draft.suggested_labels)}",
                f"- Proposal count: {draft.proposal_count}",
                f"- Draft ref: `{output_ref}`",
                "- First red-team note: "
                + (draft.red_team_notes[0] if draft.red_team_notes else "none"),
                "",
            ]
        )
    lines.extend(
        [
            "## Required Next Gates",
            "",
            *(f"- {gate}" for gate in report.required_next_gates),
            "",
            "## Boundary Flags",
            "",
            f"- Manual creation required: {report.manual_creation_required}",
            f"- GitHub issue created: {report.github_issue_created}",
            f"- GitHub PR created: {report.github_pr_created}",
            f"- GitHub write performed: {report.github_write_performed}",
            f"- Sibling repo write performed: {report.sibling_repo_write_performed}",
            f"- Promotion authorized: {report.promotion_authorized}",
            f"- Lake write performed: {report.lake_write_performed}",
            f"- SQLite write performed: {report.sqlite_write_performed}",
            f"- External writes performed: {report.external_writes_performed}",
            f"- Silent learning performed: {report.silent_learning_performed}",
            "",
            "This report is local draft text only. It does not create issues, open PRs, write sibling repos, promote canon, admit Lake records, or apply learning.",
            "",
        ]
    )
    return "\n".join(lines)


def run_cross_repo_owner_issue_drafts(
    *,
    owner_adoption_report_path: str | Path,
    out_dir: str | Path,
) -> tuple[CrossRepoOwnerIssueDraftReport, Path]:
    report_path = Path(owner_adoption_report_path)
    owner_adoption_report = CrossRepoOwnerAdoptionReport.model_validate(load_json(report_path))
    packet_refs = owner_adoption_report.packet_output_refs
    packets = [_load_packet(packet_ref) for packet_ref in packet_refs]

    run_dir = Path(out_dir)
    draft_dir = run_dir / CROSS_REPO_OWNER_ISSUE_DRAFT_DIRNAME
    draft_dir.mkdir(parents=True, exist_ok=True)
    drafts_jsonl_path = run_dir / CROSS_REPO_OWNER_ISSUE_DRAFTS_FILENAME
    if drafts_jsonl_path.exists():
        drafts_jsonl_path.unlink()

    draft_output_refs: list[str] = []
    draft_records: list[CrossRepoOwnerIssueDraft] = []
    for packet, packet_ref in zip(packets, packet_refs, strict=True):
        draft = _draft_for_packet(packet=packet, packet_ref=packet_ref)
        draft_records.append(draft)
        slug = _owner_slug(draft.target_repo)
        json_path = draft_dir / f"{slug}.issue_draft.json"
        markdown_path = draft_dir / f"{slug}.issue_draft.md"
        write_json(json_path, draft.model_dump(mode="json"))
        markdown_path.write_text(draft.issue_body_markdown, encoding="utf-8")
        append_jsonl(drafts_jsonl_path, draft.model_dump(mode="json"))
        draft_output_refs.append(str(markdown_path))

    report = build_cross_repo_owner_issue_drafts(
        owner_adoption_report=owner_adoption_report,
        owner_adoption_report_ref=str(report_path),
        packets=packets,
        packet_refs=packet_refs,
        draft_output_refs=draft_output_refs,
    )
    # Reuse the drafts already written so IDs and bodies remain identical.
    report = report.model_copy(update={"drafts": draft_records})
    write_json(
        run_dir / CROSS_REPO_OWNER_ISSUE_DRAFT_REPORT_FILENAME, report.model_dump(mode="json")
    )
    (run_dir / CROSS_REPO_OWNER_ISSUE_DRAFT_NOTES_FILENAME).write_text(
        render_cross_repo_owner_issue_draft_report(report),
        encoding="utf-8",
    )
    return report, run_dir
